class JSON_Format{
    USUARIO_POST = (USUARIO,CONTRASEÑA)=>{
        return JSON.stringify({user: USUARIO,pass: CONTRASEÑA});
    }
    USUARIO_PUT = (NUSUARIO,CONTRASEÑA)=>{
        return JSON.stringify({NUSER: NUSUARIO,PASS: CONTRASEÑA});
    }

    UBICACION_VIOLENCIA_POST_Y_PUT =(UBIVIOLENCIA)=>{
        return JSON.stringify({UVIOLENCIA:UBIVIOLENCIA});
    }

    TRATAMIENTO_POST_Y_PUT =(TRATAMIENTO)=>{
        return  JSON.stringify({TRATA: TRATAMIENTO});
    }

    TIPO_VIOLENCIA_POST_Y_PUT =(TIPOVIOLENCIA)=>{
        return  JSON.stringify({TIPOV: TIPOVIOLENCIA});
    }

    TIPO_CONDICION_POST_Y_PUT =(CONDICION)=>{
        return JSON.stringify({COND: CONDICION});
    }

    TERAPEUTAS_POST_Y_PUT =(NOMBRE)=>{
        return JSON.stringify({NOMB: NOMBRE});
    }

    REMISION_POST_Y_PUT =(REMISION)=>{
        return JSON.stringify({JUEZ: REMISION});
    }

    RECURSOS_MUNICIPALES_POST_Y_PUT =(RECURSOSMUNICIPALES)=>{
        return JSON.stringify({RECURSO: RECURSOSMUNICIPALES});
    }

    PACIENTES_POST_Y_PUT =(IDENTIDAD,NOMBRE,APELLIDO,ED,GEN,OFI,ESTADOC,REMUNERACION,EDUCACION)=>{
        return JSON.stringify({IDEN: IDENTIDAD,NOMB: NOMBRE,APELL: APELLIDO,
                               EDAD: ED,GENERO: GEN,OFICIO: OFI,ESTADOCIVIL: ESTADOC,
                               REMUNERA: REMUNERACION,EDUACION: EDUCACION});
    }

    MUNICIPIO_POST_Y_PUT =(MUNICIPALIDAD)=>{
        return JSON.stringify({MUNI: MUNICIPALIDAD});
    }

    ESTADO_OCUPACION_POST_Y_PUT = (ESTADOOCUPACION)=>{
        return JSON.stringify({ESTADO: ESTADOOCUPACION});
    }

    ESTADO_CIVIL_POST_Y_PUT =(ESTADOCIVIL)=>{
        return JSON.stringify({ESTADO: ESTADOCIVIL});
    }

    ESTADO_ATENCION_POST_Y_PUT =(ESTADOATENCION)=>{
        return JSON.stringify({ESTADO:ESTADOATENCION});
    }

    EDUCACION_POST_Y_PUT =(EDUACION)=>{
        return JSON.stringify({EDU: EDUACION});
    }

    CAUSA_VIOLENCIA_POST_Y_PUT =(CAUSAVIOLENCIA)=>{
        return JSON.stringify({CAUSA: CAUSAVIOLENCIA});
    }

    CASOS_POST_Y_PUT = (NUMEXPE,CANTBEN,IDUVIOLEN,IDEATEN,IDMUNICI,IDREMIS,IDRECUR,IDCAUSAV,IDTERAPE,IDPACIE,IDCONDIC) =>{
        return JSON.stringify({NUMEXP: NUMEXPE,CANTB: CANTBEN,IDUVIO: IDUVIOLEN
            ,IDEAT: IDEATEN,IDMUNI: IDMUNICI,IDREMI: IDREMIS,IDREC: IDRECUR,IDCAUSA: IDCAUSAV,IDTERA: IDTERAPE
            ,IDPAC: IDPACIE,IDCOND: IDCONDIC});
    }

    CASOS_TIPO_VIOLENCIA_POST_PUT = (IDCASOS, IDTIPOVIOLENCIA)=>{
        return JSON.stringify({IDCASO: IDCASOS, IDTVIO: IDTIPOVIOLENCIA});
    }

    
}

module.exports = JSON_Format;