-- MySQL Script generated by MySQL Workbench
-- vie 30 ago 2019 00:29:16 CST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema CARITAS
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema CARITAS
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `CARITAS` DEFAULT CHARACTER SET utf8 ;
USE `CARITAS` ;

-- -----------------------------------------------------
-- Table `CARITAS`.`CAUSA_VIOLENCIA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CARITAS`.`CAUSA_VIOLENCIA` (
  `id_causa` INT(11) NOT NULL AUTO_INCREMENT,
  `causa` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id_causa`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `CARITAS`.`ESTADO_ATENCION`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CARITAS`.`ESTADO_ATENCION` (
  `id_estadoa` INT(11) NOT NULL AUTO_INCREMENT,
  `estado` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id_estadoa`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `CARITAS`.`MUNICIPIO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CARITAS`.`MUNICIPIO` (
  `id_municipio` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id_municipio`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `CARITAS`.`DEPARTAMENTOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CARITAS`.`DEPARTAMENTOS` (
  `id_departamento` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id_departamento`))
ENGINE = InnoDB
AUTO_INCREMENT = 19
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `CARITAS`.`EDUCACION`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CARITAS`.`EDUCACION` (
  `id_educacion` INT(11) NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id_educacion`))
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `CARITAS`.`ESTADO_CIVIL`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CARITAS`.`ESTADO_CIVIL` (
  `id_estadoc` INT(11) NOT NULL AUTO_INCREMENT,
  `estado` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id_estadoc`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `CARITAS`.`ESTADO_OCUPACION`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CARITAS`.`ESTADO_OCUPACION` (
  `id_estado` INT(11) NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id_estado`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `CARITAS`.`PACIENTE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CARITAS`.`PACIENTE` (
  `id_paciente` INT(11) NOT NULL AUTO_INCREMENT,
  `identidad` VARCHAR(15) NULL DEFAULT NULL,
  `nombres` VARCHAR(50) NULL DEFAULT NULL,
  `apellidos` VARCHAR(50) NULL DEFAULT NULL,
  `edad` INT(8) NULL DEFAULT NULL,
  `genero` CHAR(1) NULL DEFAULT NULL,
  `oficio` VARCHAR(45) NULL DEFAULT NULL,
  `id_estadoc` INT(11) NOT NULL,
  `id_estado` INT(11) NOT NULL,
  `id_educacion` INT(11) NOT NULL,
  `id_departamento` INT(11) NOT NULL,
  PRIMARY KEY (`id_paciente`),
  INDEX `fk_PACIENTE_ESTADO_CIVIL_idx` (`id_estadoc` ASC),
  INDEX `fk_PACIENTE_ESTADO_OCUPACION1_idx` (`id_estado` ASC),
  INDEX `fk_PACIENTE_EDUCACION1_idx` (`id_educacion` ASC),
  INDEX `fk_PACIENTE_DEPARTAMENTO_idx` (`id_departamento` ASC),
  CONSTRAINT `fk_PACIENTE_DEPARTAMENTO`
    FOREIGN KEY (`id_departamento`)
    REFERENCES `CARITAS`.`DEPARTAMENTOS` (`id_departamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PACIENTE_EDUCACION1`
    FOREIGN KEY (`id_educacion`)
    REFERENCES `CARITAS`.`EDUCACION` (`id_educacion`),
  CONSTRAINT `fk_PACIENTE_ESTADO_CIVIL`
    FOREIGN KEY (`id_estadoc`)
    REFERENCES `CARITAS`.`ESTADO_CIVIL` (`id_estadoc`),
  CONSTRAINT `fk_PACIENTE_ESTADO_OCUPACION1`
    FOREIGN KEY (`id_estado`)
    REFERENCES `CARITAS`.`ESTADO_OCUPACION` (`id_estado`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `CARITAS`.`RECURSOS_MUNICIPALES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CARITAS`.`RECURSOS_MUNICIPALES` (
  `id_recursos` INT(11) NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id_recursos`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `CARITAS`.`REMISION`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CARITAS`.`REMISION` (
  `id_remision` INT(11) NOT NULL AUTO_INCREMENT,
  `juez` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id_remision`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `CARITAS`.`TERAPEUTA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CARITAS`.`TERAPEUTA` (
  `id_terapeuta` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id_terapeuta`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `CARITAS`.`TIPO_CONDICION`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CARITAS`.`TIPO_CONDICION` (
  `id_condicion` INT(11) NOT NULL AUTO_INCREMENT,
  `condicion` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id_condicion`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `CARITAS`.`TRATAMIENTO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CARITAS`.`TRATAMIENTO` (
  `id_tratamiento` INT(11) NOT NULL AUTO_INCREMENT,
  `tratamiento` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id_tratamiento`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `CARITAS`.`UBICACION_VIOLENCIA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CARITAS`.`UBICACION_VIOLENCIA` (
  `id_uviolencia` INT(11) NOT NULL AUTO_INCREMENT,
  `ubicacion` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id_uviolencia`))
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `CARITAS`.`CASO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CARITAS`.`CASO` (
  `id_caso` INT(11) NOT NULL AUTO_INCREMENT,
  `numero_expediente` VARCHAR(45) NULL DEFAULT NULL,
  `cantidad_beneficiados` INT(11) NULL DEFAULT NULL,
  `id_uviolencia` INT(11) NOT NULL,
  `id_estadoa` INT(11) NOT NULL,
  `id_municipio` INT(11) NOT NULL,
  `id_remision` INT(11) NOT NULL,
  `id_recursos` INT(11) NOT NULL,
  `id_causa` INT(11) NOT NULL,
  `id_terapeuta` INT(11) NOT NULL,
  `id_paciente` INT(11) NOT NULL,
  `id_condicion` INT(11) NOT NULL,
  `id_tratamiento` INT(11) NOT NULL,
  PRIMARY KEY (`id_caso`),
  INDEX `fk_CASO_UBICACION_VIOLENCIA1_idx` (`id_uviolencia` ASC),
  INDEX `fk_CASO_ESTADO_ATENCION1_idx` (`id_estadoa` ASC),
  INDEX `fk_CASO_MUNICIPIO1_idx` (`id_municipio` ASC),
  INDEX `fk_CASO_REMISION1_idx` (`id_remision` ASC),
  INDEX `fk_CASO_RECURSOS_MUNICIPALES1_idx` (`id_recursos` ASC),
  INDEX `fk_CASO_CAUSA_VIOLENCIA1_idx` (`id_causa` ASC),
  INDEX `fk_CASO_TERAPEUTA1_idx` (`id_terapeuta` ASC),
  INDEX `fk_CASO_PACIENTE1_idx` (`id_paciente` ASC),
  INDEX `fk_CASO_TIPO_CONDICION1_idx` (`id_condicion` ASC),
  INDEX `fk_CASO_TRATAMIENTO1_idx` (`id_tratamiento` ASC),
  CONSTRAINT `fk_CASO_CAUSA_VIOLENCIA1`
    FOREIGN KEY (`id_causa`)
    REFERENCES `CARITAS`.`CAUSA_VIOLENCIA` (`id_causa`),
  CONSTRAINT `fk_CASO_ESTADO_ATENCION1`
    FOREIGN KEY (`id_estadoa`)
    REFERENCES `CARITAS`.`ESTADO_ATENCION` (`id_estadoa`),
  CONSTRAINT `fk_CASO_MUNICIPIO1`
    FOREIGN KEY (`id_municipio`)
    REFERENCES `CARITAS`.`MUNICIPIO` (`id_municipio`),
  CONSTRAINT `fk_CASO_PACIENTE1`
    FOREIGN KEY (`id_paciente`)
    REFERENCES `CARITAS`.`PACIENTE` (`id_paciente`),
  CONSTRAINT `fk_CASO_RECURSOS_MUNICIPALES1`
    FOREIGN KEY (`id_recursos`)
    REFERENCES `CARITAS`.`RECURSOS_MUNICIPALES` (`id_recursos`),
  CONSTRAINT `fk_CASO_REMISION1`
    FOREIGN KEY (`id_remision`)
    REFERENCES `CARITAS`.`REMISION` (`id_remision`),
  CONSTRAINT `fk_CASO_TERAPEUTA1`
    FOREIGN KEY (`id_terapeuta`)
    REFERENCES `CARITAS`.`TERAPEUTA` (`id_terapeuta`),
  CONSTRAINT `fk_CASO_TIPO_CONDICION1`
    FOREIGN KEY (`id_condicion`)
    REFERENCES `CARITAS`.`TIPO_CONDICION` (`id_condicion`),
  CONSTRAINT `fk_CASO_TRATAMIENTO1`
    FOREIGN KEY (`id_tratamiento`)
    REFERENCES `CARITAS`.`TRATAMIENTO` (`id_tratamiento`),
  CONSTRAINT `fk_CASO_UBICACION_VIOLENCIA1`
    FOREIGN KEY (`id_uviolencia`)
    REFERENCES `CARITAS`.`UBICACION_VIOLENCIA` (`id_uviolencia`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `CARITAS`.`TIPO_VIOLENCIA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CARITAS`.`TIPO_VIOLENCIA` (
  `id_tipoviolencia` INT(11) NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id_tipoviolencia`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `CARITAS`.`CASO_TIPO_VIOLENCIA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CARITAS`.`CASO_TIPO_VIOLENCIA` (
  `id_caso` INT(11) NOT NULL,
  `id_tipoviolencia` INT(11) NOT NULL,
  INDEX `fk_CASO_has_TIPO_VIOLENCIA_TIPO_VIOLENCIA1_idx` (`id_tipoviolencia` ASC),
  INDEX `fk_CASO_has_TIPO_VIOLENCIA_CASO1_idx` (`id_caso` ASC),
  CONSTRAINT `fk_CASO_has_TIPO_VIOLENCIA_CASO1`
    FOREIGN KEY (`id_caso`)
    REFERENCES `CARITAS`.`CASO` (`id_caso`),
  CONSTRAINT `fk_CASO_has_TIPO_VIOLENCIA_TIPO_VIOLENCIA1`
    FOREIGN KEY (`id_tipoviolencia`)
    REFERENCES `CARITAS`.`TIPO_VIOLENCIA` (`id_tipoviolencia`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `CARITAS`.`USUARIO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CARITAS`.`USUARIO` (
  `usuario` VARCHAR(45) NOT NULL,
  `contraseña` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`usuario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

USE `CARITAS` ;

-- -----------------------------------------------------
-- Placeholder table for view `CARITAS`.`VIEW_CASO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CARITAS`.`VIEW_CASO` (`id_caso` INT, `nombre` INT, `condicion` INT, `terapeuta` INT, `causa` INT, `recursos` INT, `juez` INT, `municipio` INT, `estado_atencion` INT, `ubicacion_violencia` INT, `tratamiento` INT);

-- -----------------------------------------------------
-- Placeholder table for view `CARITAS`.`VIEW_CAUSA_VIOLENCIA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CARITAS`.`VIEW_CAUSA_VIOLENCIA` (`id_causa` INT, `causa` INT);

-- -----------------------------------------------------
-- Placeholder table for view `CARITAS`.`VIEW_DEPARTAMENTO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CARITAS`.`VIEW_DEPARTAMENTO` (`id_departamento` INT, `nombre` INT);

-- -----------------------------------------------------
-- Placeholder table for view `CARITAS`.`VIEW_EDUCACION`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CARITAS`.`VIEW_EDUCACION` (`id_educacion` INT, `tipo` INT);

-- -----------------------------------------------------
-- Placeholder table for view `CARITAS`.`VIEW_ESTADO_ATENCION`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CARITAS`.`VIEW_ESTADO_ATENCION` (`id_estadoa` INT, `estado` INT);

-- -----------------------------------------------------
-- Placeholder table for view `CARITAS`.`VIEW_ESTADO_CIVIL`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CARITAS`.`VIEW_ESTADO_CIVIL` (`id_estadoc` INT, `estado` INT);

-- -----------------------------------------------------
-- Placeholder table for view `CARITAS`.`VIEW_ESTADO_OCUPACION`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CARITAS`.`VIEW_ESTADO_OCUPACION` (`id_estado` INT, `tipo` INT);

-- -----------------------------------------------------
-- Placeholder table for view `CARITAS`.`VIEW_MUNICIPIO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CARITAS`.`VIEW_MUNICIPIO` (`id_municipio` INT, `nombre` INT);

-- -----------------------------------------------------
-- Placeholder table for view `CARITAS`.`VIEW_PACIENTE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CARITAS`.`VIEW_PACIENTE` (`id_paciente` INT, `identidad` INT, `nombre` INT, `apellido` INT, `edad` INT, `genero` INT, `oficio` INT, `estado_civil` INT, `trabajo` INT, `educacion` INT);

-- -----------------------------------------------------
-- Placeholder table for view `CARITAS`.`VIEW_RECURSOS_MUNICIPALES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CARITAS`.`VIEW_RECURSOS_MUNICIPALES` (`id_recursos` INT, `tipo` INT);

-- -----------------------------------------------------
-- Placeholder table for view `CARITAS`.`VIEW_REMISION`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CARITAS`.`VIEW_REMISION` (`id_recursos` INT, `tipo` INT);

-- -----------------------------------------------------
-- Placeholder table for view `CARITAS`.`VIEW_TERAPEUTA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CARITAS`.`VIEW_TERAPEUTA` (`id_terapeuta` INT, `nombre` INT);

-- -----------------------------------------------------
-- Placeholder table for view `CARITAS`.`VIEW_TIPO_CONDICION`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CARITAS`.`VIEW_TIPO_CONDICION` (`id_condicion` INT, `condicion` INT);

-- -----------------------------------------------------
-- Placeholder table for view `CARITAS`.`VIEW_TIPO_VIOLENCIA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CARITAS`.`VIEW_TIPO_VIOLENCIA` (`id_tipoviolencia` INT, `tipo` INT);

-- -----------------------------------------------------
-- Placeholder table for view `CARITAS`.`VIEW_TRATAMIENTO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CARITAS`.`VIEW_TRATAMIENTO` (`id_tratamiento` INT, `tratamiento` INT);

-- -----------------------------------------------------
-- Placeholder table for view `CARITAS`.`VIEW_UBICACION_VIOLENCIA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CARITAS`.`VIEW_UBICACION_VIOLENCIA` (`id_uviolencia` INT, `ubicacion` INT);

-- -----------------------------------------------------
-- Placeholder table for view `CARITAS`.`VIEW_USUARIO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CARITAS`.`VIEW_USUARIO` (`usuario` INT, `contraseña` INT);

-- -----------------------------------------------------
-- procedure CREATE_CASO
-- -----------------------------------------------------

DELIMITER $$
USE `CARITAS`$$
CREATE DEFINER=`caritas`@`localhost` PROCEDURE `CREATE_CASO`(NUMEXP VARCHAR(45),CANTB INT,
IDUVIO INT,IDEAT INT,IDMUNI INT,IDREMI INT,IDREC INT,IDCAUSA INT,IDTERA INT
,IDPAC INT,IDCOND INT,IDTRATA INT)
BEGIN
insert into CASO (numero_expediente,cantidad_beneficiados
,id_uviolencia,id_estadoa,id_municipio,
id_remision,id_recursos
,id_causa,id_terapeuta,id_paciente,id_condicion,id_tratamiento)
values (NUMEXP,CANTB,IDUVIO,IDEAT,IDMUNI,IDREMI,IDREC,IDCAUSA,IDTERA,IDPAC,IDCOND,IDTRATA);
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure CREATE_CASO_TIPO_VIOLENCIA
-- -----------------------------------------------------

DELIMITER $$
USE `CARITAS`$$
CREATE DEFINER=`caritas`@`localhost` PROCEDURE `CREATE_CASO_TIPO_VIOLENCIA`(IDCASO INT, IDTVIO INT)
BEGIN
insert into CASO_TIPO_VIOLENCIA (id_caso,id_tipoviolencia) values (IDCASO,IDTVIO);
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure CREATE_CAUSA_VIOLENCIA
-- -----------------------------------------------------

DELIMITER $$
USE `CARITAS`$$
CREATE DEFINER=`caritas`@`localhost` PROCEDURE `CREATE_CAUSA_VIOLENCIA`(CAUSA VARCHAR(45))
BEGIN
insert into CAUSA_VIOLENCIA (causa) values (CAUSA);
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure CREATE_DEPARTAMENTO
-- -----------------------------------------------------

DELIMITER $$
USE `CARITAS`$$
CREATE DEFINER=`caritas`@`localhost` PROCEDURE `CREATE_DEPARTAMENTO`(DEP VARCHAR(45))
BEGIN
	insert into DEPARTAMENTOS (nombre) values (DEP); 
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure CREATE_EDUCACION
-- -----------------------------------------------------

DELIMITER $$
USE `CARITAS`$$
CREATE DEFINER=`caritas`@`localhost` PROCEDURE `CREATE_EDUCACION`(EDU VARCHAR(45))
BEGIN
insert into EDUCACION (tipo) values (EDU);
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure CREATE_ESTADO_ATENCION
-- -----------------------------------------------------

DELIMITER $$
USE `CARITAS`$$
CREATE DEFINER=`caritas`@`localhost` PROCEDURE `CREATE_ESTADO_ATENCION`(ESTADO VARCHAR(45))
BEGIN
insert into ESTADO_ATENCION (estado) values (ESTADO);
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure CREATE_ESTADO_CIVIL
-- -----------------------------------------------------

DELIMITER $$
USE `CARITAS`$$
CREATE DEFINER=`caritas`@`localhost` PROCEDURE `CREATE_ESTADO_CIVIL`(ESTADO VARCHAR(45))
BEGIN
insert into ESTADO_CIVIL (estado) values (ESTADO);
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure CREATE_ESTADO_OCUPACION
-- -----------------------------------------------------

DELIMITER $$
USE `CARITAS`$$
CREATE DEFINER=`caritas`@`localhost` PROCEDURE `CREATE_ESTADO_OCUPACION`(ESTADO VARCHAR(45))
BEGIN
insert into ESTADO_OCUPACION (tipo) values (ESTADO);
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure CREATE_MUNICIPIO
-- -----------------------------------------------------

DELIMITER $$
USE `CARITAS`$$
CREATE DEFINER=`caritas`@`localhost` PROCEDURE `CREATE_MUNICIPIO`(MUNI VARCHAR(45))
BEGIN
insert into MUNICIPIO (nombre) values (MUNI);

END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure CREATE_PACIENTE
-- -----------------------------------------------------

DELIMITER $$
USE `CARITAS`$$
CREATE DEFINER=`caritas`@`localhost` PROCEDURE `CREATE_PACIENTE`(IDEN VARCHAR(15),NOMB VARCHAR(50),APELL VARCHAR(50),EDAD INT
,GENERO CHAR,OFICIO VARCHAR(45),ESTADOCIVIL INT,REMUNERA INT,EDUACION INT,DEP INT)
BEGIN
insert into PACIENTE (identidad,nombres,apellidos,edad,genero,oficio,id_estadoc,id_estado,id_educacion,id_departamento)
values(IDEN,NOMB,APELL,EDAD,GENERO,OFICIO,ESTADOCIVIL,REMUNERA,EDUCACION,DEP);
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure CREATE_RECURSOS_MUNICIPALES
-- -----------------------------------------------------

DELIMITER $$
USE `CARITAS`$$
CREATE DEFINER=`caritas`@`localhost` PROCEDURE `CREATE_RECURSOS_MUNICIPALES`(RECURSO VARCHAR(45))
BEGIN
insert into RECURSOS_MUNICIPALES (tipo) values (RECURSO);
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure CREATE_REMISION
-- -----------------------------------------------------

DELIMITER $$
USE `CARITAS`$$
CREATE DEFINER=`caritas`@`localhost` PROCEDURE `CREATE_REMISION`(JUEZ VARCHAR(45))
BEGIN
insert into REMISION (juez) values (JUEZ);
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure CREATE_TERAPEUTA
-- -----------------------------------------------------

DELIMITER $$
USE `CARITAS`$$
CREATE DEFINER=`caritas`@`localhost` PROCEDURE `CREATE_TERAPEUTA`(NOMB VARCHAR(45))
BEGIN
insert into TERAPEUTA (nombre) values (NOMB);
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure CREATE_TIPO_CONDICION
-- -----------------------------------------------------

DELIMITER $$
USE `CARITAS`$$
CREATE DEFINER=`caritas`@`localhost` PROCEDURE `CREATE_TIPO_CONDICION`(COND VARCHAR(45))
BEGIN
insert into TIPO_CONDICION (condicion) values (COND);
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure CREATE_TIPO_VIOLENCIA
-- -----------------------------------------------------

DELIMITER $$
USE `CARITAS`$$
CREATE DEFINER=`caritas`@`localhost` PROCEDURE `CREATE_TIPO_VIOLENCIA`(TIPOV VARCHAR(45))
BEGIN
insert into TIPO_VIOLENCIA (tipo) values(TIPOV);
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure CREATE_TRATAMIENTO
-- -----------------------------------------------------

DELIMITER $$
USE `CARITAS`$$
CREATE DEFINER=`caritas`@`localhost` PROCEDURE `CREATE_TRATAMIENTO`(TRATA VARCHAR(45))
BEGIN
insert into TRATAMIENTO (tratamiento) values (TRATA);
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure CREATE_UBICACION_VIOLENCIA
-- -----------------------------------------------------

DELIMITER $$
USE `CARITAS`$$
CREATE DEFINER=`caritas`@`localhost` PROCEDURE `CREATE_UBICACION_VIOLENCIA`(UVIOLENCIA VARCHAR(45))
BEGIN
insert into UBICACION_VIOLENCIA (ubicacion) values (UVIOLENCIA);
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure CREATE_USUARIO
-- -----------------------------------------------------

DELIMITER $$
USE `CARITAS`$$
CREATE DEFINER=`caritas`@`localhost` PROCEDURE `CREATE_USUARIO`(user varchar(45),pass varchar(45))
BEGIN
insert into USUARIO (usuario,contraseña) values (user,pass);

END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure DATOS_CASO
-- -----------------------------------------------------

DELIMITER $$
USE `CARITAS`$$
CREATE DEFINER=`caritas`@`localhost` PROCEDURE `DATOS_CASO`(ID INT)
BEGIN
select id_uviolencia,id_estadoa,id_municipio,id_remision,id_recursos,id_causa,id_terapeuta,
id_paciente,id_condicion,id_tratamiento from CASO where id_caso = ID;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure DATOS_PACIENTE
-- -----------------------------------------------------

DELIMITER $$
USE `CARITAS`$$
CREATE DEFINER=`caritas`@`localhost` PROCEDURE `DATOS_PACIENTE`(ID INT)
BEGIN
select id_estadoc, id_estado, id_educacion, id_departamento from PACIENTE where id_paciente =ID;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure DELETE_CASO
-- -----------------------------------------------------

DELIMITER $$
USE `CARITAS`$$
CREATE DEFINER=`caritas`@`localhost` PROCEDURE `DELETE_CASO`(ID INT)
BEGIN
delete from CASO where id_caso = ID;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure DELETE_CASO_TIPO_VIOLENCIA
-- -----------------------------------------------------

DELIMITER $$
USE `CARITAS`$$
CREATE DEFINER=`caritas`@`localhost` PROCEDURE `DELETE_CASO_TIPO_VIOLENCIA`(IDCASO INT)
BEGIN
delete from CASO_TIPO_VIOLENCIA where id_caso = IDCASO;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure DELETE_CAUSA_VIOLENCIA
-- -----------------------------------------------------

DELIMITER $$
USE `CARITAS`$$
CREATE DEFINER=`caritas`@`localhost` PROCEDURE `DELETE_CAUSA_VIOLENCIA`(ID INT)
BEGIN
delete from CAUSA_VIOLENCIA where id_causa = ID;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure DELETE_DEPARTAMENTO
-- -----------------------------------------------------

DELIMITER $$
USE `CARITAS`$$
CREATE DEFINER=`caritas`@`localhost` PROCEDURE `DELETE_DEPARTAMENTO`(ID INT)
BEGIN
	delete from DEPARTAMENTOS where id_departamento = ID;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure DELETE_EDUCACION
-- -----------------------------------------------------

DELIMITER $$
USE `CARITAS`$$
CREATE DEFINER=`caritas`@`localhost` PROCEDURE `DELETE_EDUCACION`(ID INT)
BEGIN
delete from EDUCACION where id_educacion = ID;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure DELETE_ESTADO_ATENCION
-- -----------------------------------------------------

DELIMITER $$
USE `CARITAS`$$
CREATE DEFINER=`caritas`@`localhost` PROCEDURE `DELETE_ESTADO_ATENCION`(ID INT)
BEGIN
delete from ESTADO_ATENCION where id_estadoa = ID;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure DELETE_ESTADO_CIVIL
-- -----------------------------------------------------

DELIMITER $$
USE `CARITAS`$$
CREATE DEFINER=`caritas`@`localhost` PROCEDURE `DELETE_ESTADO_CIVIL`(ID INT)
BEGIN
delete from ESTADO_CIVIL where id_estadoc = ID;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure DELETE_ESTADO_OCUPACION
-- -----------------------------------------------------

DELIMITER $$
USE `CARITAS`$$
CREATE DEFINER=`caritas`@`localhost` PROCEDURE `DELETE_ESTADO_OCUPACION`(ID INT)
BEGIN
delete from ESTADO_OCUPACION where id_estado = ID;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure DELETE_MUNICIPIO
-- -----------------------------------------------------

DELIMITER $$
USE `CARITAS`$$
CREATE DEFINER=`caritas`@`localhost` PROCEDURE `DELETE_MUNICIPIO`(ID INT)
BEGIN
delete from MUNICIPIO where id_municipio = ID;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure DELETE_PACIENTE
-- -----------------------------------------------------

DELIMITER $$
USE `CARITAS`$$
CREATE DEFINER=`caritas`@`localhost` PROCEDURE `DELETE_PACIENTE`(ID INT)
BEGIN
delete from PACIENTE where id_paciente = ID;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure DELETE_RECURSOS_MUNICIPALES
-- -----------------------------------------------------

DELIMITER $$
USE `CARITAS`$$
CREATE DEFINER=`caritas`@`localhost` PROCEDURE `DELETE_RECURSOS_MUNICIPALES`(ID INT)
BEGIN
delete from RECURSOS_MUNICIPALES where id_recursos = ID;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure DELETE_REMISION
-- -----------------------------------------------------

DELIMITER $$
USE `CARITAS`$$
CREATE DEFINER=`caritas`@`localhost` PROCEDURE `DELETE_REMISION`(ID INT)
BEGIN
delete from REMISION where id_remision = ID;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure DELETE_TERAPEUTA
-- -----------------------------------------------------

DELIMITER $$
USE `CARITAS`$$
CREATE DEFINER=`caritas`@`localhost` PROCEDURE `DELETE_TERAPEUTA`(ID INT)
BEGIN
delete from TERAPEUTA where id_terapeuta = ID;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure DELETE_TIPO_CONDICION
-- -----------------------------------------------------

DELIMITER $$
USE `CARITAS`$$
CREATE DEFINER=`caritas`@`localhost` PROCEDURE `DELETE_TIPO_CONDICION`(ID INT)
BEGIN
delete from TIPO_CONDICION where id_condicion = ID;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure DELETE_TIPO_VIOLENCIA
-- -----------------------------------------------------

DELIMITER $$
USE `CARITAS`$$
CREATE DEFINER=`caritas`@`localhost` PROCEDURE `DELETE_TIPO_VIOLENCIA`(ID INT)
BEGIN
delete from TIPO_VIOLENCIA where id_tipoviolencia = ID;

END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure DELETE_TRATAMIENTO
-- -----------------------------------------------------

DELIMITER $$
USE `CARITAS`$$
CREATE DEFINER=`caritas`@`localhost` PROCEDURE `DELETE_TRATAMIENTO`(ID INT)
BEGIN
delete from TRATAMIENTO where id_tratamiento = ID;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure DELETE_UBICACION_VIOLENCIA
-- -----------------------------------------------------

DELIMITER $$
USE `CARITAS`$$
CREATE DEFINER=`caritas`@`localhost` PROCEDURE `DELETE_UBICACION_VIOLENCIA`(ID INT)
BEGIN
delete from UBICACION_VIOLENCIA where id_uviolencia = ID;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure DELETE_USUARIO
-- -----------------------------------------------------

DELIMITER $$
USE `CARITAS`$$
CREATE DEFINER=`caritas`@`localhost` PROCEDURE `DELETE_USUARIO`(USER VARCHAR(45))
BEGIN
delete from USUARIO where usuario = USER;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure MOSTRAR_VIOLENCIAxCASO
-- -----------------------------------------------------

DELIMITER $$
USE `CARITAS`$$
CREATE DEFINER=`caritas`@`localhost` PROCEDURE `MOSTRAR_VIOLENCIAxCASO`(ID INT)
BEGIN
select tv.tipo as violencia from CASO cs 
inner join CASO_TIPO_VIOLENCIA ctp on cs.id_caso = ctp.id_caso
inner join TIPO_VIOLENCIA tv on ctp.id_tipoviolencia = tv.id_tipoviolencia
where cs.id_caso = ID;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure UPDATE_CASO
-- -----------------------------------------------------

DELIMITER $$
USE `CARITAS`$$
CREATE DEFINER=`caritas`@`localhost` PROCEDURE `UPDATE_CASO`(ID INT,NUMEXP VARCHAR(45),CANTB INT,
IDUVIO INT,IDEAT INT,IDMUNI INT,IDREMI INT,IDREC INT,IDCAUSA INT,IDTERA INT
,IDPAC INT,IDCOND INT,IDTRATA INT)
BEGIN
update CASO set numero_expediente=NUMEXP,cantidad_beneficiados=CANTB,
id_uviolencia = IDUVIO,id_estadoa=IDEAT,id_municipio=IDMUNI,
id_remision=IDREMI,id_recursos=IDREC,id_causa=IDCAUSA,
id_terapeuta=IDTERA,id_paciente=IDPAC,id_condicion=IDCOND,id_tratamiento=IDTRATA
where id_caso = ID;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure UPDATE_CASO_TIPO_VIOLENCIA
-- -----------------------------------------------------

DELIMITER $$
USE `CARITAS`$$
CREATE DEFINER=`caritas`@`localhost` PROCEDURE `UPDATE_CASO_TIPO_VIOLENCIA`(IDCASO INT, IDTVIO INT)
BEGIN
update CASO_TIPO_VIOLENCIA set id_tipoviolencia = IDTVIO where id_caso = IDCASO;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure UPDATE_CAUSA_VIOLENCIA
-- -----------------------------------------------------

DELIMITER $$
USE `CARITAS`$$
CREATE DEFINER=`caritas`@`localhost` PROCEDURE `UPDATE_CAUSA_VIOLENCIA`(ID INT,CAUSA VARCHAR(45))
BEGIN
update CAUSA_VIOLENCIA set causa = CAUSA where id_causa = ID;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure UPDATE_DEPARTAMENTO
-- -----------------------------------------------------

DELIMITER $$
USE `CARITAS`$$
CREATE DEFINER=`caritas`@`localhost` PROCEDURE `UPDATE_DEPARTAMENTO`(ID INT, DEP VARCHAR(45))
BEGIN
	update DEPARTAMENTOS set nombre = DEP where id_departamento = ID;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure UPDATE_EDUCACION
-- -----------------------------------------------------

DELIMITER $$
USE `CARITAS`$$
CREATE DEFINER=`caritas`@`localhost` PROCEDURE `UPDATE_EDUCACION`(ID INT, EDU VARCHAR(45))
BEGIN
update EDUCACION set tipo = EDU where id_educacion = ID;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure UPDATE_ESTADO_ATENCION
-- -----------------------------------------------------

DELIMITER $$
USE `CARITAS`$$
CREATE DEFINER=`caritas`@`localhost` PROCEDURE `UPDATE_ESTADO_ATENCION`(ID INT)
BEGIN
update ESTADO_ATENCION set estado = ESTADO where id_estadoa = ID;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure UPDATE_ESTADO_CIVIL
-- -----------------------------------------------------

DELIMITER $$
USE `CARITAS`$$
CREATE DEFINER=`caritas`@`localhost` PROCEDURE `UPDATE_ESTADO_CIVIL`(ID INT,ESTADO VARCHAR(45))
BEGIN
update ESTADO_CIVIL set estado = ESTADO where id_estadoc = ID;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure UPDATE_ESTADO_OCUPACION
-- -----------------------------------------------------

DELIMITER $$
USE `CARITAS`$$
CREATE DEFINER=`caritas`@`localhost` PROCEDURE `UPDATE_ESTADO_OCUPACION`(ID INT, OCUPA VARCHAR(45))
BEGIN
update ESTADO_OCUPACION set tipo = OCUPA where id_estado = ID;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure UPDATE_MUNICIPIO
-- -----------------------------------------------------

DELIMITER $$
USE `CARITAS`$$
CREATE DEFINER=`caritas`@`localhost` PROCEDURE `UPDATE_MUNICIPIO`(ID INT, MUNI VARCHAR(45))
BEGIN
update MUNICIPIO set nombre = MUNI where id_municipio = ID;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure UPDATE_PACIENTE
-- -----------------------------------------------------

DELIMITER $$
USE `CARITAS`$$
CREATE DEFINER=`caritas`@`localhost` PROCEDURE `UPDATE_PACIENTE`(ID INT,IDEN VARCHAR(15),NOMB VARCHAR(50),APELL VARCHAR(50),EDAD INT
,GENERO CHAR,OFICIO VARCHAR(45),ESTADOCIVIL INT,REMUNERA INT,EDUACION INT,DEP INT)
BEGIN
update PACIENTE set identidad = IDEN, nombres = NOMB, apellidos = APELL,edad = EDAD,genero = GENERO,
oficio = OFICIO, id_estadoc = ESTADOCIVIL, id_estado = REMUNERA, id_educacion = EDUACION, id_departamento = DEP where id_paciente = ID;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure UPDATE_RECURSOS_MUNICIPALES
-- -----------------------------------------------------

DELIMITER $$
USE `CARITAS`$$
CREATE DEFINER=`caritas`@`localhost` PROCEDURE `UPDATE_RECURSOS_MUNICIPALES`(ID INT, RECURSO VARCHAR(45))
BEGIN
update RECURSOS_MUNICIPALES set tipo = RECURSO where id_recursos=ID;

END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure UPDATE_REMISION
-- -----------------------------------------------------

DELIMITER $$
USE `CARITAS`$$
CREATE DEFINER=`caritas`@`localhost` PROCEDURE `UPDATE_REMISION`(ID INT,JUEZ VARCHAR(45))
BEGIN
update REMISION set juez = JUEZ where id_remision = ID;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure UPDATE_TERAPEUTA
-- -----------------------------------------------------

DELIMITER $$
USE `CARITAS`$$
CREATE DEFINER=`caritas`@`localhost` PROCEDURE `UPDATE_TERAPEUTA`(ID INT, NOMB VARCHAR(45))
BEGIN
update TERAPEUTA set nombre = NOMB where id_terapeuta = ID;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure UPDATE_TIPO_CONDICION
-- -----------------------------------------------------

DELIMITER $$
USE `CARITAS`$$
CREATE DEFINER=`caritas`@`localhost` PROCEDURE `UPDATE_TIPO_CONDICION`(ID INT,COND VARCHAR(45))
BEGIN
update TIPO_CONDICION set condicion = COND where id_condicion = ID;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure UPDATE_TIPO_VIOLENCIA
-- -----------------------------------------------------

DELIMITER $$
USE `CARITAS`$$
CREATE DEFINER=`caritas`@`localhost` PROCEDURE `UPDATE_TIPO_VIOLENCIA`(ID INT,TIPOV VARCHAR(45))
BEGIN
update TIPO_VIOLENCIA set tipo = TIPOV where id_tipoviolencia = ID;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure UPDATE_TRATAMIENTO
-- -----------------------------------------------------

DELIMITER $$
USE `CARITAS`$$
CREATE DEFINER=`caritas`@`localhost` PROCEDURE `UPDATE_TRATAMIENTO`(ID INT,TRATA VARCHAR(45))
BEGIN
update TRATAMIENTO set tratamiento = TRATA WHERE id_tratamiento= ID;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure UPDATE_UBICACION_VIOLENCIA
-- -----------------------------------------------------

DELIMITER $$
USE `CARITAS`$$
CREATE DEFINER=`caritas`@`localhost` PROCEDURE `UPDATE_UBICACION_VIOLENCIA`(ID INT,UVIOLENCIA VARCHAR(45))
BEGIN
update UBICACION_VIOLENCIA set ubicacion = UVIOLENCIA where id_uviolencia = ID;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure UPDATE_USUARIO
-- -----------------------------------------------------

DELIMITER $$
USE `CARITAS`$$
CREATE DEFINER=`caritas`@`localhost` PROCEDURE `UPDATE_USUARIO`(USER VARCHAR(45),PASS VARCHAR(45),NUSER VARCHAR(45))
BEGIN
update USUARIO set usuario = NUSER, contraseña = PASS where usuario = USER;

END$$

DELIMITER ;

-- -----------------------------------------------------
-- View `CARITAS`.`VIEW_CASO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CARITAS`.`VIEW_CASO`;
USE `CARITAS`;
CREATE  OR REPLACE ALGORITHM=UNDEFINED DEFINER=`caritas`@`localhost` SQL SECURITY DEFINER VIEW `CARITAS`.`VIEW_CASO` AS select `cs`.`id_caso` AS `id_caso`,concat(`pc`.`nombres`,' ',`pc`.`apellidos`) AS `nombre`,`tc`.`condicion` AS `condicion`,`tr`.`nombre` AS `terapeuta`,`cv`.`causa` AS `causa`,`rmp`.`tipo` AS `recursos`,`rm`.`juez` AS `juez`,`mn`.`nombre` AS `municipio`,`ea`.`estado` AS `estado_atencion`,`uv`.`ubicacion` AS `ubicacion_violencia`,`trm`.`tratamiento` AS `tratamiento` from ((((((((((`CARITAS`.`CASO` `cs` join `CARITAS`.`UBICACION_VIOLENCIA` `uv` on((`cs`.`id_uviolencia` = `uv`.`id_uviolencia`))) join `CARITAS`.`ESTADO_ATENCION` `ea` on((`cs`.`id_estadoa` = `ea`.`id_estadoa`))) join `CARITAS`.`MUNICIPIO` `mn` on((`cs`.`id_municipio` = `mn`.`id_municipio`))) join `CARITAS`.`REMISION` `rm` on((`cs`.`id_remision` = `rm`.`id_remision`))) join `CARITAS`.`RECURSOS_MUNICIPALES` `rmp` on((`cs`.`id_recursos` = `rmp`.`id_recursos`))) join `CARITAS`.`CAUSA_VIOLENCIA` `cv` on((`cs`.`id_causa` = `cv`.`id_causa`))) join `CARITAS`.`TERAPEUTA` `tr` on((`cs`.`id_terapeuta` = `tr`.`id_terapeuta`))) join `CARITAS`.`PACIENTE` `pc` on((`cs`.`id_paciente` = `pc`.`id_paciente`))) join `CARITAS`.`TIPO_CONDICION` `tc` on((`cs`.`id_condicion` = `tc`.`id_condicion`))) join `CARITAS`.`TRATAMIENTO` `trm` on((`cs`.`id_tratamiento` = `trm`.`id_tratamiento`)));

-- -----------------------------------------------------
-- View `CARITAS`.`VIEW_CAUSA_VIOLENCIA`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CARITAS`.`VIEW_CAUSA_VIOLENCIA`;
USE `CARITAS`;
CREATE  OR REPLACE ALGORITHM=UNDEFINED DEFINER=`caritas`@`localhost` SQL SECURITY DEFINER VIEW `CARITAS`.`VIEW_CAUSA_VIOLENCIA` AS select `CARITAS`.`CAUSA_VIOLENCIA`.`id_causa` AS `id_causa`,`CARITAS`.`CAUSA_VIOLENCIA`.`causa` AS `causa` from `CARITAS`.`CAUSA_VIOLENCIA`;

-- -----------------------------------------------------
-- View `CARITAS`.`VIEW_DEPARTAMENTO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CARITAS`.`VIEW_DEPARTAMENTO`;
USE `CARITAS`;
CREATE  OR REPLACE ALGORITHM=UNDEFINED DEFINER=`caritas`@`localhost` SQL SECURITY DEFINER VIEW `CARITAS`.`VIEW_DEPARTAMENTO` AS select `CARITAS`.`DEPARTAMENTOS`.`id_departamento` AS `id_departamento`,`CARITAS`.`DEPARTAMENTOS`.`nombre` AS `nombre` from `CARITAS`.`DEPARTAMENTOS`;

-- -----------------------------------------------------
-- View `CARITAS`.`VIEW_EDUCACION`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CARITAS`.`VIEW_EDUCACION`;
USE `CARITAS`;
CREATE  OR REPLACE ALGORITHM=UNDEFINED DEFINER=`caritas`@`localhost` SQL SECURITY DEFINER VIEW `CARITAS`.`VIEW_EDUCACION` AS select `CARITAS`.`EDUCACION`.`id_educacion` AS `id_educacion`,`CARITAS`.`EDUCACION`.`tipo` AS `tipo` from `CARITAS`.`EDUCACION`;

-- -----------------------------------------------------
-- View `CARITAS`.`VIEW_ESTADO_ATENCION`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CARITAS`.`VIEW_ESTADO_ATENCION`;
USE `CARITAS`;
CREATE  OR REPLACE ALGORITHM=UNDEFINED DEFINER=`caritas`@`localhost` SQL SECURITY DEFINER VIEW `CARITAS`.`VIEW_ESTADO_ATENCION` AS select `CARITAS`.`ESTADO_ATENCION`.`id_estadoa` AS `id_estadoa`,`CARITAS`.`ESTADO_ATENCION`.`estado` AS `estado` from `CARITAS`.`ESTADO_ATENCION`;

-- -----------------------------------------------------
-- View `CARITAS`.`VIEW_ESTADO_CIVIL`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CARITAS`.`VIEW_ESTADO_CIVIL`;
USE `CARITAS`;
CREATE  OR REPLACE ALGORITHM=UNDEFINED DEFINER=`caritas`@`localhost` SQL SECURITY DEFINER VIEW `CARITAS`.`VIEW_ESTADO_CIVIL` AS select `CARITAS`.`ESTADO_CIVIL`.`id_estadoc` AS `id_estadoc`,`CARITAS`.`ESTADO_CIVIL`.`estado` AS `estado` from `CARITAS`.`ESTADO_CIVIL`;

-- -----------------------------------------------------
-- View `CARITAS`.`VIEW_ESTADO_OCUPACION`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CARITAS`.`VIEW_ESTADO_OCUPACION`;
USE `CARITAS`;
CREATE  OR REPLACE ALGORITHM=UNDEFINED DEFINER=`caritas`@`localhost` SQL SECURITY DEFINER VIEW `CARITAS`.`VIEW_ESTADO_OCUPACION` AS select `CARITAS`.`ESTADO_OCUPACION`.`id_estado` AS `id_estado`,`CARITAS`.`ESTADO_OCUPACION`.`tipo` AS `tipo` from `CARITAS`.`ESTADO_OCUPACION`;

-- -----------------------------------------------------
-- View `CARITAS`.`VIEW_MUNICIPIO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CARITAS`.`VIEW_MUNICIPIO`;
USE `CARITAS`;
CREATE  OR REPLACE ALGORITHM=UNDEFINED DEFINER=`caritas`@`localhost` SQL SECURITY DEFINER VIEW `CARITAS`.`VIEW_MUNICIPIO` AS select `CARITAS`.`MUNICIPIO`.`id_municipio` AS `id_municipio`,`CARITAS`.`MUNICIPIO`.`nombre` AS `nombre` from `CARITAS`.`MUNICIPIO`;

-- -----------------------------------------------------
-- View `CARITAS`.`VIEW_PACIENTE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CARITAS`.`VIEW_PACIENTE`;
USE `CARITAS`;
CREATE  OR REPLACE ALGORITHM=UNDEFINED DEFINER=`caritas`@`localhost` SQL SECURITY DEFINER VIEW `CARITAS`.`VIEW_PACIENTE` AS select `pc`.`id_paciente` AS `id_paciente`,`pc`.`identidad` AS `identidad`,`pc`.`nombres` AS `nombre`,`pc`.`apellidos` AS `apellido`,`pc`.`edad` AS `edad`,`pc`.`genero` AS `genero`,`pc`.`oficio` AS `oficio`,`ec`.`estado` AS `estado_civil`,`eo`.`tipo` AS `trabajo`,`ed`.`tipo` AS `educacion` from (((`CARITAS`.`PACIENTE` `pc` join `CARITAS`.`ESTADO_CIVIL` `ec` on((`pc`.`id_estadoc` = `ec`.`id_estadoc`))) join `CARITAS`.`ESTADO_OCUPACION` `eo` on((`pc`.`id_estado` = `eo`.`id_estado`))) join `CARITAS`.`EDUCACION` `ed` on((`pc`.`id_educacion` = `ed`.`id_educacion`)));

-- -----------------------------------------------------
-- View `CARITAS`.`VIEW_RECURSOS_MUNICIPALES`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CARITAS`.`VIEW_RECURSOS_MUNICIPALES`;
USE `CARITAS`;
CREATE  OR REPLACE ALGORITHM=UNDEFINED DEFINER=`caritas`@`localhost` SQL SECURITY DEFINER VIEW `CARITAS`.`VIEW_RECURSOS_MUNICIPALES` AS select `CARITAS`.`RECURSOS_MUNICIPALES`.`id_recursos` AS `id_recursos`,`CARITAS`.`RECURSOS_MUNICIPALES`.`tipo` AS `tipo` from `CARITAS`.`RECURSOS_MUNICIPALES`;

-- -----------------------------------------------------
-- View `CARITAS`.`VIEW_REMISION`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CARITAS`.`VIEW_REMISION`;
USE `CARITAS`;
CREATE  OR REPLACE ALGORITHM=UNDEFINED DEFINER=`caritas`@`localhost` SQL SECURITY DEFINER VIEW `CARITAS`.`VIEW_REMISION` AS select `CARITAS`.`RECURSOS_MUNICIPALES`.`id_recursos` AS `id_recursos`,`CARITAS`.`RECURSOS_MUNICIPALES`.`tipo` AS `tipo` from `CARITAS`.`RECURSOS_MUNICIPALES`;

-- -----------------------------------------------------
-- View `CARITAS`.`VIEW_TERAPEUTA`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CARITAS`.`VIEW_TERAPEUTA`;
USE `CARITAS`;
CREATE  OR REPLACE ALGORITHM=UNDEFINED DEFINER=`caritas`@`localhost` SQL SECURITY DEFINER VIEW `CARITAS`.`VIEW_TERAPEUTA` AS select `CARITAS`.`TERAPEUTA`.`id_terapeuta` AS `id_terapeuta`,`CARITAS`.`TERAPEUTA`.`nombre` AS `nombre` from `CARITAS`.`TERAPEUTA`;

-- -----------------------------------------------------
-- View `CARITAS`.`VIEW_TIPO_CONDICION`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CARITAS`.`VIEW_TIPO_CONDICION`;
USE `CARITAS`;
CREATE  OR REPLACE ALGORITHM=UNDEFINED DEFINER=`caritas`@`localhost` SQL SECURITY DEFINER VIEW `CARITAS`.`VIEW_TIPO_CONDICION` AS select `CARITAS`.`TIPO_CONDICION`.`id_condicion` AS `id_condicion`,`CARITAS`.`TIPO_CONDICION`.`condicion` AS `condicion` from `CARITAS`.`TIPO_CONDICION`;

-- -----------------------------------------------------
-- View `CARITAS`.`VIEW_TIPO_VIOLENCIA`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CARITAS`.`VIEW_TIPO_VIOLENCIA`;
USE `CARITAS`;
CREATE  OR REPLACE ALGORITHM=UNDEFINED DEFINER=`caritas`@`localhost` SQL SECURITY DEFINER VIEW `CARITAS`.`VIEW_TIPO_VIOLENCIA` AS select `CARITAS`.`TIPO_VIOLENCIA`.`id_tipoviolencia` AS `id_tipoviolencia`,`CARITAS`.`TIPO_VIOLENCIA`.`tipo` AS `tipo` from `CARITAS`.`TIPO_VIOLENCIA`;

-- -----------------------------------------------------
-- View `CARITAS`.`VIEW_TRATAMIENTO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CARITAS`.`VIEW_TRATAMIENTO`;
USE `CARITAS`;
CREATE  OR REPLACE ALGORITHM=UNDEFINED DEFINER=`caritas`@`localhost` SQL SECURITY DEFINER VIEW `CARITAS`.`VIEW_TRATAMIENTO` AS select `CARITAS`.`TRATAMIENTO`.`id_tratamiento` AS `id_tratamiento`,`CARITAS`.`TRATAMIENTO`.`tratamiento` AS `tratamiento` from `CARITAS`.`TRATAMIENTO`;

-- -----------------------------------------------------
-- View `CARITAS`.`VIEW_UBICACION_VIOLENCIA`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CARITAS`.`VIEW_UBICACION_VIOLENCIA`;
USE `CARITAS`;
CREATE  OR REPLACE ALGORITHM=UNDEFINED DEFINER=`caritas`@`localhost` SQL SECURITY DEFINER VIEW `CARITAS`.`VIEW_UBICACION_VIOLENCIA` AS select `CARITAS`.`UBICACION_VIOLENCIA`.`id_uviolencia` AS `id_uviolencia`,`CARITAS`.`UBICACION_VIOLENCIA`.`ubicacion` AS `ubicacion` from `CARITAS`.`UBICACION_VIOLENCIA`;

-- -----------------------------------------------------
-- View `CARITAS`.`VIEW_USUARIO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CARITAS`.`VIEW_USUARIO`;
USE `CARITAS`;
CREATE  OR REPLACE ALGORITHM=UNDEFINED DEFINER=`caritas`@`localhost` SQL SECURITY DEFINER VIEW `CARITAS`.`VIEW_USUARIO` AS select `CARITAS`.`USUARIO`.`usuario` AS `usuario`,`CARITAS`.`USUARIO`.`contraseña` AS `contraseña` from `CARITAS`.`USUARIO`;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


-- -----------------------------------------------------
-- Data for table `CARITAS`.`CAUSA_VIOLENCIA`
-- -----------------------------------------------------
START TRANSACTION;
USE `CARITAS`;
INSERT INTO `CARITAS`.`CAUSA_VIOLENCIA` (`id_causa`, `causa`) VALUES (1, 'Economica');
INSERT INTO `CARITAS`.`CAUSA_VIOLENCIA` (`id_causa`, `causa`) VALUES (2, 'Infidelidad');
INSERT INTO `CARITAS`.`CAUSA_VIOLENCIA` (`id_causa`, `causa`) VALUES (3, 'Alcholismo');

COMMIT;


-- -----------------------------------------------------
-- Data for table `CARITAS`.`TERAPEUTA`
-- -----------------------------------------------------
START TRANSACTION;
USE `CARITAS`;
INSERT INTO `CARITAS`.`TERAPEUTA` (`id_terapeuta`, `nombre`) VALUES (1, 'Miriam Fonseca');
INSERT INTO `CARITAS`.`TERAPEUTA` (`id_terapeuta`, `nombre`) VALUES (2, 'Nataly Valle');

COMMIT;


-- -----------------------------------------------------
-- Data for table `CARITAS`.`ESTADO_CIVIL`
-- -----------------------------------------------------
START TRANSACTION;
USE `CARITAS`;
INSERT INTO `CARITAS`.`ESTADO_CIVIL` (`id_estadoc`, `estado`) VALUES (1, 'Casado');
INSERT INTO `CARITAS`.`ESTADO_CIVIL` (`id_estadoc`, `estado`) VALUES (2, 'Soltero');
INSERT INTO `CARITAS`.`ESTADO_CIVIL` (`id_estadoc`, `estado`) VALUES (3, 'Union Libre');

COMMIT;


-- -----------------------------------------------------
-- Data for table `CARITAS`.`ESTADO_OCUPACION`
-- -----------------------------------------------------
START TRANSACTION;
USE `CARITAS`;
INSERT INTO `CARITAS`.`ESTADO_OCUPACION` (`id_estado`, `tipo`) VALUES (1, 'Trabajo Remunerado');
INSERT INTO `CARITAS`.`ESTADO_OCUPACION` (`id_estado`, `tipo`) VALUES (2, 'Trabajo No-Remunerado');

COMMIT;


-- -----------------------------------------------------
-- Data for table `CARITAS`.`EDUCACION`
-- -----------------------------------------------------
START TRANSACTION;
USE `CARITAS`;
INSERT INTO `CARITAS`.`EDUCACION` (`id_educacion`, `tipo`) VALUES (1, 'Analfabeta');
INSERT INTO `CARITAS`.`EDUCACION` (`id_educacion`, `tipo`) VALUES (2, 'Pre-Basica Incompleta');
INSERT INTO `CARITAS`.`EDUCACION` (`id_educacion`, `tipo`) VALUES (3, 'Pre-Basica Completa');
INSERT INTO `CARITAS`.`EDUCACION` (`id_educacion`, `tipo`) VALUES (4, 'Basica Incompleta');
INSERT INTO `CARITAS`.`EDUCACION` (`id_educacion`, `tipo`) VALUES (5, 'Basica Completa');
INSERT INTO `CARITAS`.`EDUCACION` (`id_educacion`, `tipo`) VALUES (6, 'Superior Incompleta');
INSERT INTO `CARITAS`.`EDUCACION` (`id_educacion`, `tipo`) VALUES (7, 'Superior Completa');

COMMIT;


-- -----------------------------------------------------
-- Data for table `CARITAS`.`TIPO_CONDICION`
-- -----------------------------------------------------
START TRANSACTION;
USE `CARITAS`;
INSERT INTO `CARITAS`.`TIPO_CONDICION` (`id_condicion`, `condicion`) VALUES (1, 'Victima');
INSERT INTO `CARITAS`.`TIPO_CONDICION` (`id_condicion`, `condicion`) VALUES (2, 'Agresor');

COMMIT;


-- -----------------------------------------------------
-- Data for table `CARITAS`.`TIPO_VIOLENCIA`
-- -----------------------------------------------------
START TRANSACTION;
USE `CARITAS`;
INSERT INTO `CARITAS`.`TIPO_VIOLENCIA` (`id_tipoviolencia`, `tipo`) VALUES (1, 'Violencia Psicologica');
INSERT INTO `CARITAS`.`TIPO_VIOLENCIA` (`id_tipoviolencia`, `tipo`) VALUES (2, 'Violencia Fisica');
INSERT INTO `CARITAS`.`TIPO_VIOLENCIA` (`id_tipoviolencia`, `tipo`) VALUES (3, 'Violencia Economica');
INSERT INTO `CARITAS`.`TIPO_VIOLENCIA` (`id_tipoviolencia`, `tipo`) VALUES (4, 'Violencia Sexual');

COMMIT;

-- -----------------------------------------------------
-- Data for table `CARITAS`.`UBICACION_VIOLENCIA`
-- -----------------------------------------------------
START TRANSACTION;
USE `CARITAS`;
INSERT INTO `CARITAS`.`UBICACION_VIOLENCIA` (`id_uviolencia`, `ubicacion`) VALUES (1, 'Urbana');
INSERT INTO `CARITAS`.`UBICACION_VIOLENCIA` (`id_uviolencia`, `ubicacion`) VALUES (2, 'Rural');

COMMIT;


-- -----------------------------------------------------
-- Data for table `CARITAS`.`ESTADO_ATENCION`
-- -----------------------------------------------------
START TRANSACTION;
USE `CARITAS`;
INSERT INTO `CARITAS`.`ESTADO_ATENCION` (`id_estadoa`, `estado`) VALUES (1, 'Proceso');
INSERT INTO `CARITAS`.`ESTADO_ATENCION` (`id_estadoa`, `estado`) VALUES (2, 'Espera');
INSERT INTO `CARITAS`.`ESTADO_ATENCION` (`id_estadoa`, `estado`) VALUES (3, 'Abandono');

COMMIT;


-- -----------------------------------------------------
-- Data for table `CARITAS`.`MUNICIPIO`
-- -----------------------------------------------------
START TRANSACTION;
USE `CARITAS`;
INSERT INTO `CARITAS`.`MUNICIPIO` (`id_municipio`, `nombre`) VALUES (1, 'San Pedro Sula');
INSERT INTO `CARITAS`.`MUNICIPIO` (`id_municipio`, `nombre`) VALUES (2, 'La Lima');
INSERT INTO `CARITAS`.`MUNICIPIO` (`id_municipio`, `nombre`) VALUES (3, 'Villanueva');

COMMIT;


-- -----------------------------------------------------
-- Data for table `CARITAS`.`REMISION`
-- -----------------------------------------------------
START TRANSACTION;
USE `CARITAS`;
INSERT INTO `CARITAS`.`REMISION` (`id_remision`, `juez`) VALUES (1, 'JEVD');
INSERT INTO `CARITAS`.`REMISION` (`id_remision`, `juez`) VALUES (2, 'JEVS');
INSERT INTO `CARITAS`.`REMISION` (`id_remision`, `juez`) VALUES (3, 'JP');

COMMIT;


-- -----------------------------------------------------
-- Data for table `CARITAS`.`RECURSOS_MUNICIPALES`
-- -----------------------------------------------------
START TRANSACTION;
USE `CARITAS`;
INSERT INTO `CARITAS`.`RECURSOS_MUNICIPALES` (`id_recursos`, `tipo`) VALUES (1, 'UMEP');
INSERT INTO `CARITAS`.`RECURSOS_MUNICIPALES` (`id_recursos`, `tipo`) VALUES (2, 'OMM');
INSERT INTO `CARITAS`.`RECURSOS_MUNICIPALES` (`id_recursos`, `tipo`) VALUES (3, 'ONG');
INSERT INTO `CARITAS`.`RECURSOS_MUNICIPALES` (`id_recursos`, `tipo`) VALUES (4, 'Juzgado');
INSERT INTO `CARITAS`.`RECURSOS_MUNICIPALES` (`id_recursos`, `tipo`) VALUES (5, 'Fiscalia');

COMMIT;


START TRANSACTION;
USE `CARITAS`;
INSERT INTO `CARITAS`.`DEPARTAMENTOS` (`id_departamento`, `nombre`) VALUES ('1', 'Atlántida');
INSERT INTO `CARITAS`.`DEPARTAMENTOS` (`id_departamento`, `nombre`) VALUES ('2', 'Choluteca');
INSERT INTO `CARITAS`.`DEPARTAMENTOS` (`id_departamento`, `nombre`) VALUES ('3', 'Colón');
INSERT INTO `CARITAS`.`DEPARTAMENTOS` (`id_departamento`, `nombre`) VALUES ('4', 'Comayagua');
INSERT INTO `CARITAS`.`DEPARTAMENTOS` (`id_departamento`, `nombre`) VALUES ('5', 'Copán');
INSERT INTO `CARITAS`.`DEPARTAMENTOS` (`id_departamento`, `nombre`) VALUES ('6', 'Cortes');
INSERT INTO `CARITAS`.`DEPARTAMENTOS` (`id_departamento`, `nombre`) VALUES ('7', 'El Paraíso');
INSERT INTO `CARITAS`.`DEPARTAMENTOS` (`id_departamento`, `nombre`) VALUES ('8', 'Francisco Morazán');
INSERT INTO `CARITAS`.`DEPARTAMENTOS` (`id_departamento`, `nombre`) VALUES ('9', 'Gracias a Dios');
INSERT INTO `CARITAS`.`DEPARTAMENTOS` (`id_departamento`, `nombre`) VALUES ('10', 'Intibucá');
INSERT INTO `CARITAS`.`DEPARTAMENTOS` (`id_departamento`, `nombre`) VALUES ('11', 'Islas de la Bahía');
INSERT INTO `CARITAS`.`DEPARTAMENTOS` (`id_departamento`, `nombre`) VALUES ('12', 'La Paz');
INSERT INTO `CARITAS`.`DEPARTAMENTOS` (`id_departamento`, `nombre`) VALUES ('13', 'Lempira');
INSERT INTO `CARITAS`.`DEPARTAMENTOS` (`id_departamento`, `nombre`) VALUES ('14', 'Ocotepeque');
INSERT INTO `CARITAS`.`DEPARTAMENTOS` (`id_departamento`, `nombre`) VALUES ('15', 'Olancho');
INSERT INTO `CARITAS`.`DEPARTAMENTOS` (`id_departamento`, `nombre`) VALUES ('16', 'Santa Bárbara');
INSERT INTO `CARITAS`.`DEPARTAMENTOS` (`id_departamento`, `nombre`) VALUES ('17', 'Valle');
INSERT INTO `CARITAS`.`DEPARTAMENTOS` (`id_departamento`, `nombre`) VALUES ('18', 'Yoro');

COMMIT;
