-- MySQL Script generated by MySQL Workbench
-- sáb 17 ago 2019 20:42:09 CST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema bjmns7kzvsnubc19qcus
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bjmns7kzvsnubc19qcus
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bjmns7kzvsnubc19qcus` DEFAULT CHARACTER SET utf8 ;
USE `bjmns7kzvsnubc19qcus` ;

-- -----------------------------------------------------
-- Table `bjmns7kzvsnubc19qcus`.`CAUSA_VIOLENCIA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bjmns7kzvsnubc19qcus`.`CAUSA_VIOLENCIA` (
  `id_causa` INT(11) NOT NULL AUTO_INCREMENT,
  `causa` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id_causa`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bjmns7kzvsnubc19qcus`.`ESTADO_ATENCION`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bjmns7kzvsnubc19qcus`.`ESTADO_ATENCION` (
  `id_estadoa` INT(11) NOT NULL AUTO_INCREMENT,
  `estado` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id_estadoa`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bjmns7kzvsnubc19qcus`.`MUNICIPIO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bjmns7kzvsnubc19qcus`.`MUNICIPIO` (
  `id_municipio` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id_municipio`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bjmns7kzvsnubc19qcus`.`EDUCACION`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bjmns7kzvsnubc19qcus`.`EDUCACION` (
  `id_educacion` INT(11) NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id_educacion`))
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bjmns7kzvsnubc19qcus`.`ESTADO_CIVIL`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bjmns7kzvsnubc19qcus`.`ESTADO_CIVIL` (
  `id_estadoc` INT(11) NOT NULL AUTO_INCREMENT,
  `estado` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id_estadoc`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bjmns7kzvsnubc19qcus`.`ESTADO_OCUPACION`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bjmns7kzvsnubc19qcus`.`ESTADO_OCUPACION` (
  `id_estado` INT(11) NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id_estado`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bjmns7kzvsnubc19qcus`.`PACIENTE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bjmns7kzvsnubc19qcus`.`PACIENTE` (
  `id_paciente` INT(11) NOT NULL AUTO_INCREMENT,
  `identidad` VARCHAR(15) NULL DEFAULT NULL,
  `nombres` VARCHAR(50) NULL DEFAULT NULL,
  `apellidos` VARCHAR(50) NULL DEFAULT NULL,
  `edad` INT(8) NULL DEFAULT NULL,
  `genero` CHAR(1) NULL DEFAULT NULL,
  `oficio` VARCHAR(45) NULL DEFAULT NULL,
  `id_estadoc` INT(11) NOT NULL,
  `id_estado` INT(11) NOT NULL,
  `id_educacion` INT(11) NOT NULL,
  PRIMARY KEY (`id_paciente`),
  INDEX `fk_PACIENTE_ESTADO_CIVIL_idx` (`id_estadoc` ASC),
  INDEX `fk_PACIENTE_ESTADO_OCUPACION1_idx` (`id_estado` ASC),
  INDEX `fk_PACIENTE_EDUCACION1_idx` (`id_educacion` ASC),
  CONSTRAINT `fk_PACIENTE_EDUCACION1`
    FOREIGN KEY (`id_educacion`)
    REFERENCES `bjmns7kzvsnubc19qcus`.`EDUCACION` (`id_educacion`),
  CONSTRAINT `fk_PACIENTE_ESTADO_CIVIL`
    FOREIGN KEY (`id_estadoc`)
    REFERENCES `bjmns7kzvsnubc19qcus`.`ESTADO_CIVIL` (`id_estadoc`),
  CONSTRAINT `fk_PACIENTE_ESTADO_OCUPACION1`
    FOREIGN KEY (`id_estado`)
    REFERENCES `bjmns7kzvsnubc19qcus`.`ESTADO_OCUPACION` (`id_estado`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bjmns7kzvsnubc19qcus`.`RECURSOS_MUNICIPALES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bjmns7kzvsnubc19qcus`.`RECURSOS_MUNICIPALES` (
  `id_recursos` INT(11) NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id_recursos`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bjmns7kzvsnubc19qcus`.`REMISION`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bjmns7kzvsnubc19qcus`.`REMISION` (
  `id_remision` INT(11) NOT NULL AUTO_INCREMENT,
  `juez` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id_remision`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bjmns7kzvsnubc19qcus`.`TERAPEUTA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bjmns7kzvsnubc19qcus`.`TERAPEUTA` (
  `id_terapeuta` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id_terapeuta`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bjmns7kzvsnubc19qcus`.`TIPO_CONDICION`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bjmns7kzvsnubc19qcus`.`TIPO_CONDICION` (
  `id_condicion` INT(11) NOT NULL AUTO_INCREMENT,
  `condicion` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id_condicion`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bjmns7kzvsnubc19qcus`.`UBICACION_VIOLENCIA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bjmns7kzvsnubc19qcus`.`UBICACION_VIOLENCIA` (
  `id_uviolencia` INT(11) NOT NULL AUTO_INCREMENT,
  `ubicacion` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id_uviolencia`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bjmns7kzvsnubc19qcus`.`CASO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bjmns7kzvsnubc19qcus`.`CASO` (
  `id_caso` INT(11) NOT NULL AUTO_INCREMENT,
  `numero_expediente` VARCHAR(45) NULL DEFAULT NULL,
  `cantidad_beneficiados` INT(11) NULL DEFAULT NULL,
  `id_uviolencia` INT(11) NOT NULL,
  `id_estadoa` INT(11) NOT NULL,
  `id_municipio` INT(11) NOT NULL,
  `id_remision` INT(11) NOT NULL,
  `id_recursos` INT(11) NOT NULL,
  `id_causa` INT(11) NOT NULL,
  `id_terapeuta` INT(11) NOT NULL,
  `id_paciente` INT(11) NOT NULL,
  `id_condicion` INT(11) NOT NULL,
  PRIMARY KEY (`id_caso`),
  INDEX `fk_CASO_UBICACION_VIOLENCIA1_idx` (`id_uviolencia` ASC),
  INDEX `fk_CASO_ESTADO_ATENCION1_idx` (`id_estadoa` ASC),
  INDEX `fk_CASO_MUNICIPIO1_idx` (`id_municipio` ASC),
  INDEX `fk_CASO_REMISION1_idx` (`id_remision` ASC),
  INDEX `fk_CASO_RECURSOS_MUNICIPALES1_idx` (`id_recursos` ASC),
  INDEX `fk_CASO_CAUSA_VIOLENCIA1_idx` (`id_causa` ASC),
  INDEX `fk_CASO_TERAPEUTA1_idx` (`id_terapeuta` ASC),
  INDEX `fk_CASO_PACIENTE1_idx` (`id_paciente` ASC),
  INDEX `fk_CASO_TIPO_CONDICION1_idx` (`id_condicion` ASC),
  CONSTRAINT `fk_CASO_CAUSA_VIOLENCIA1`
    FOREIGN KEY (`id_causa`)
    REFERENCES `bjmns7kzvsnubc19qcus`.`CAUSA_VIOLENCIA` (`id_causa`),
  CONSTRAINT `fk_CASO_ESTADO_ATENCION1`
    FOREIGN KEY (`id_estadoa`)
    REFERENCES `bjmns7kzvsnubc19qcus`.`ESTADO_ATENCION` (`id_estadoa`),
  CONSTRAINT `fk_CASO_MUNICIPIO1`
    FOREIGN KEY (`id_municipio`)
    REFERENCES `bjmns7kzvsnubc19qcus`.`MUNICIPIO` (`id_municipio`),
  CONSTRAINT `fk_CASO_PACIENTE1`
    FOREIGN KEY (`id_paciente`)
    REFERENCES `bjmns7kzvsnubc19qcus`.`PACIENTE` (`id_paciente`),
  CONSTRAINT `fk_CASO_RECURSOS_MUNICIPALES1`
    FOREIGN KEY (`id_recursos`)
    REFERENCES `bjmns7kzvsnubc19qcus`.`RECURSOS_MUNICIPALES` (`id_recursos`),
  CONSTRAINT `fk_CASO_REMISION1`
    FOREIGN KEY (`id_remision`)
    REFERENCES `bjmns7kzvsnubc19qcus`.`REMISION` (`id_remision`),
  CONSTRAINT `fk_CASO_TERAPEUTA1`
    FOREIGN KEY (`id_terapeuta`)
    REFERENCES `bjmns7kzvsnubc19qcus`.`TERAPEUTA` (`id_terapeuta`),
  CONSTRAINT `fk_CASO_TIPO_CONDICION1`
    FOREIGN KEY (`id_condicion`)
    REFERENCES `bjmns7kzvsnubc19qcus`.`TIPO_CONDICION` (`id_condicion`),
  CONSTRAINT `fk_CASO_UBICACION_VIOLENCIA1`
    FOREIGN KEY (`id_uviolencia`)
    REFERENCES `bjmns7kzvsnubc19qcus`.`UBICACION_VIOLENCIA` (`id_uviolencia`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bjmns7kzvsnubc19qcus`.`TIPO_VIOLENCIA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bjmns7kzvsnubc19qcus`.`TIPO_VIOLENCIA` (
  `id_tipoviolencia` INT(11) NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id_tipoviolencia`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bjmns7kzvsnubc19qcus`.`CASO_TIPO_VIOLENCIA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bjmns7kzvsnubc19qcus`.`CASO_TIPO_VIOLENCIA` (
  `id_caso` INT(11) NOT NULL,
  `id_tipoviolencia` INT(11) NOT NULL,
  INDEX `fk_CASO_has_TIPO_VIOLENCIA_TIPO_VIOLENCIA1_idx` (`id_tipoviolencia` ASC),
  INDEX `fk_CASO_has_TIPO_VIOLENCIA_CASO1_idx` (`id_caso` ASC),
  CONSTRAINT `fk_CASO_has_TIPO_VIOLENCIA_CASO1`
    FOREIGN KEY (`id_caso`)
    REFERENCES `bjmns7kzvsnubc19qcus`.`CASO` (`id_caso`),
  CONSTRAINT `fk_CASO_has_TIPO_VIOLENCIA_TIPO_VIOLENCIA1`
    FOREIGN KEY (`id_tipoviolencia`)
    REFERENCES `bjmns7kzvsnubc19qcus`.`TIPO_VIOLENCIA` (`id_tipoviolencia`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bjmns7kzvsnubc19qcus`.`USUARIO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bjmns7kzvsnubc19qcus`.`USUARIO` (
  `usuario` VARCHAR(45) NOT NULL,
  `contraseña` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`usuario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

USE `bjmns7kzvsnubc19qcus` ;

-- -----------------------------------------------------
-- Placeholder table for view `bjmns7kzvsnubc19qcus`.`VIEW_CASO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bjmns7kzvsnubc19qcus`.`VIEW_CASO` (`nombre` INT, `condicion` INT, `terapeuta` INT, `causa` INT, `recursos` INT, `juez` INT, `municipio` INT, `estado_atencion` INT, `ubicacion_violencia` INT);

-- -----------------------------------------------------
-- Placeholder table for view `bjmns7kzvsnubc19qcus`.`VIEW_CAUSA_VIOLENCIA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bjmns7kzvsnubc19qcus`.`VIEW_CAUSA_VIOLENCIA` (`id_causa` INT, `causa` INT);

-- -----------------------------------------------------
-- Placeholder table for view `bjmns7kzvsnubc19qcus`.`VIEW_EDUCACION`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bjmns7kzvsnubc19qcus`.`VIEW_EDUCACION` (`id_educacion` INT, `tipo` INT);

-- -----------------------------------------------------
-- Placeholder table for view `bjmns7kzvsnubc19qcus`.`VIEW_ESTADO_ATENCION`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bjmns7kzvsnubc19qcus`.`VIEW_ESTADO_ATENCION` (`id_estadoa` INT, `estado` INT);

-- -----------------------------------------------------
-- Placeholder table for view `bjmns7kzvsnubc19qcus`.`VIEW_ESTADO_CIVIL`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bjmns7kzvsnubc19qcus`.`VIEW_ESTADO_CIVIL` (`id_estadoc` INT, `estado` INT);

-- -----------------------------------------------------
-- Placeholder table for view `bjmns7kzvsnubc19qcus`.`VIEW_ESTADO_OCUPACION`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bjmns7kzvsnubc19qcus`.`VIEW_ESTADO_OCUPACION` (`id_estado` INT, `tipo` INT);

-- -----------------------------------------------------
-- Placeholder table for view `bjmns7kzvsnubc19qcus`.`VIEW_MUNICIPIO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bjmns7kzvsnubc19qcus`.`VIEW_MUNICIPIO` (`id_municipio` INT, `nombre` INT);

-- -----------------------------------------------------
-- Placeholder table for view `bjmns7kzvsnubc19qcus`.`VIEW_PACIENTE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bjmns7kzvsnubc19qcus`.`VIEW_PACIENTE` (`identidad` INT, `nombre` INT, `apellido` INT, `edad` INT, `genero` INT, `oficio` INT, `estado_civil` INT, `trabajo` INT, `educacion` INT);

-- -----------------------------------------------------
-- Placeholder table for view `bjmns7kzvsnubc19qcus`.`VIEW_RECURSOS_MUNICIPALES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bjmns7kzvsnubc19qcus`.`VIEW_RECURSOS_MUNICIPALES` (`id_recursos` INT, `tipo` INT);

-- -----------------------------------------------------
-- Placeholder table for view `bjmns7kzvsnubc19qcus`.`VIEW_REMISION`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bjmns7kzvsnubc19qcus`.`VIEW_REMISION` (`id_recursos` INT, `tipo` INT);

-- -----------------------------------------------------
-- Placeholder table for view `bjmns7kzvsnubc19qcus`.`VIEW_TERAPEUTA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bjmns7kzvsnubc19qcus`.`VIEW_TERAPEUTA` (`id_terapeuta` INT, `nombre` INT);

-- -----------------------------------------------------
-- Placeholder table for view `bjmns7kzvsnubc19qcus`.`VIEW_TIPO_CONDICION`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bjmns7kzvsnubc19qcus`.`VIEW_TIPO_CONDICION` (`id_condicion` INT, `condicion` INT);

-- -----------------------------------------------------
-- Placeholder table for view `bjmns7kzvsnubc19qcus`.`VIEW_TIPO_VIOLENCIA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bjmns7kzvsnubc19qcus`.`VIEW_TIPO_VIOLENCIA` (`id_tipoviolencia` INT, `tipo` INT);

-- -----------------------------------------------------
-- Placeholder table for view `bjmns7kzvsnubc19qcus`.`VIEW_UBICACION_VIOLENCIA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bjmns7kzvsnubc19qcus`.`VIEW_UBICACION_VIOLENCIA` (`id_uviolencia` INT, `ubicacion` INT);

-- -----------------------------------------------------
-- Placeholder table for view `bjmns7kzvsnubc19qcus`.`VIEW_USUARIO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bjmns7kzvsnubc19qcus`.`VIEW_USUARIO` (`usuario` INT, `contraseña` INT);

-- -----------------------------------------------------
-- procedure CREATE_CASO
-- -----------------------------------------------------

DELIMITER $$
USE `bjmns7kzvsnubc19qcus`$$
CREATE DEFINER=`ug1byw8l46zz27st`@`%` PROCEDURE `CREATE_CASO`(NUMEXP VARCHAR(45),CANTB INT,
IDUVIO INT,IDEAT INT,IDMUNI INT,IDREMI INT,IDREC INT,IDCAUSA INT,IDTERA INT
,IDPAC INT,IDCOND INT)
BEGIN
insert into CASO (numero_expediente,cantidad_beneficiados
,id_uviolencia,id_estadoa,id_municipio,
id_remision,id_recursos
,id_causa,id_terapeuta,id_paciente,id_condicion)
values (NUMEXP,CANTB,IDUVIO,IDEAT,IDMUNI,IDREMI,IDREC,IDCAUSA,IDTERA,IDPAC,IDCOND);
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure CREATE_CASO_TIPO_VIOLENCIA
-- -----------------------------------------------------

DELIMITER $$
USE `bjmns7kzvsnubc19qcus`$$
CREATE DEFINER=`ug1byw8l46zz27st`@`%` PROCEDURE `CREATE_CASO_TIPO_VIOLENCIA`(IDCASO INT, IDTVIO INT)
BEGIN
insert into CASO_TIPO_VIOLENCIA (id_caso,id_tipoviolencia) values (IDCASO,IDTVIO);
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure CREATE_CAUSA_VIOLENCIA
-- -----------------------------------------------------

DELIMITER $$
USE `bjmns7kzvsnubc19qcus`$$
CREATE DEFINER=`ug1byw8l46zz27st`@`%` PROCEDURE `CREATE_CAUSA_VIOLENCIA`(CAUSA VARCHAR(45))
BEGIN
insert into CAUSA_VIOLENCIA (causa) values (CAUSA);
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure CREATE_EDUCACION
-- -----------------------------------------------------

DELIMITER $$
USE `bjmns7kzvsnubc19qcus`$$
CREATE DEFINER=`ug1byw8l46zz27st`@`%` PROCEDURE `CREATE_EDUCACION`(EDU VARCHAR(45))
BEGIN
insert into EDUCACION (tipo) values (EDU);
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure CREATE_ESTADO_ATENCION
-- -----------------------------------------------------

DELIMITER $$
USE `bjmns7kzvsnubc19qcus`$$
CREATE DEFINER=`ug1byw8l46zz27st`@`%` PROCEDURE `CREATE_ESTADO_ATENCION`(ESTADO VARCHAR(45))
BEGIN
insert into ESTADO_ATENCION (estado) values (ESTADO);
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure CREATE_ESTADO_CIVIL
-- -----------------------------------------------------

DELIMITER $$
USE `bjmns7kzvsnubc19qcus`$$
CREATE DEFINER=`ug1byw8l46zz27st`@`%` PROCEDURE `CREATE_ESTADO_CIVIL`(ESTADO VARCHAR(45))
BEGIN
insert into ESTADO_CIVIL (estado) values (ESTADO);
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure CREATE_ESTADO_OCUPACION
-- -----------------------------------------------------

DELIMITER $$
USE `bjmns7kzvsnubc19qcus`$$
CREATE DEFINER=`ug1byw8l46zz27st`@`%` PROCEDURE `CREATE_ESTADO_OCUPACION`(ESTADO VARCHAR(45))
BEGIN
insert into ESTADO_OCUPACION (tipo) values (ESTADO);
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure CREATE_MUNICIPIO
-- -----------------------------------------------------

DELIMITER $$
USE `bjmns7kzvsnubc19qcus`$$
CREATE DEFINER=`ug1byw8l46zz27st`@`%` PROCEDURE `CREATE_MUNICIPIO`(MUNI VARCHAR(45))
BEGIN
insert into MUNICIPIO (nombre) values (MUNI);

END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure CREATE_PACIENTE
-- -----------------------------------------------------

DELIMITER $$
USE `bjmns7kzvsnubc19qcus`$$
CREATE DEFINER=`ug1byw8l46zz27st`@`%` PROCEDURE `CREATE_PACIENTE`(IDEN VARCHAR(15),NOMB VARCHAR(50),APELL VARCHAR(50),EDAD INT
,GENERO CHAR,OFICIO VARCHAR(45),ESTADOCIVIL INT,REMUNERA INT,EDUACION INT)
BEGIN
insert into PACIENTE (identidad,nombres,apellidos,edad,genero,oficio,id_estadoc,id_estado,id_educacion)
values(IDEN,NOMB,APELL,EDAD,GENERO,OFICIO,ESTADOCIVIL,REMUNERA,EDUCACION);
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure CREATE_RECURSOS_MUNICIPALES
-- -----------------------------------------------------

DELIMITER $$
USE `bjmns7kzvsnubc19qcus`$$
CREATE DEFINER=`ug1byw8l46zz27st`@`%` PROCEDURE `CREATE_RECURSOS_MUNICIPALES`(RECURSO VARCHAR(45))
BEGIN
insert into RECURSOS_MUNICIPALES (tipo) values (RECURSO);
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure CREATE_REMISION
-- -----------------------------------------------------

DELIMITER $$
USE `bjmns7kzvsnubc19qcus`$$
CREATE DEFINER=`ug1byw8l46zz27st`@`%` PROCEDURE `CREATE_REMISION`(JUEZ VARCHAR(45))
BEGIN
insert into REMISION (juez) values (JUEZ);
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure CREATE_TERAPEUTA
-- -----------------------------------------------------

DELIMITER $$
USE `bjmns7kzvsnubc19qcus`$$
CREATE DEFINER=`ug1byw8l46zz27st`@`%` PROCEDURE `CREATE_TERAPEUTA`(NOMB VARCHAR(45))
BEGIN
insert into TERAPEUTA (nombre) values (NOMB);
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure CREATE_TIPO_CONDICION
-- -----------------------------------------------------

DELIMITER $$
USE `bjmns7kzvsnubc19qcus`$$
CREATE DEFINER=`ug1byw8l46zz27st`@`%` PROCEDURE `CREATE_TIPO_CONDICION`(COND VARCHAR(45))
BEGIN
insert into TIPO_CONDICION (condicion) values (COND);
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure CREATE_TIPO_VIOLENCIA
-- -----------------------------------------------------

DELIMITER $$
USE `bjmns7kzvsnubc19qcus`$$
CREATE DEFINER=`ug1byw8l46zz27st`@`%` PROCEDURE `CREATE_TIPO_VIOLENCIA`(TIPOV VARCHAR(45))
BEGIN
insert into TIPO_VIOLENCIA (tipo) values(TIPOV);
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure CREATE_UBICACION_VIOLENCIA
-- -----------------------------------------------------

DELIMITER $$
USE `bjmns7kzvsnubc19qcus`$$
CREATE DEFINER=`ug1byw8l46zz27st`@`%` PROCEDURE `CREATE_UBICACION_VIOLENCIA`(UVIOLENCIA VARCHAR(45))
BEGIN
insert into UBICACION_VIOLENCIA (ubicacion) values (UVIOLENCIA);
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure CREATE_USUARIO
-- -----------------------------------------------------

DELIMITER $$
USE `bjmns7kzvsnubc19qcus`$$
CREATE DEFINER=`ug1byw8l46zz27st`@`%` PROCEDURE `CREATE_USUARIO`(user varchar(45),pass varchar(45))
BEGIN
insert into USUARIO (usuario,contraseña) values (user,pass);

END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure DELETE_CASO
-- -----------------------------------------------------

DELIMITER $$
USE `bjmns7kzvsnubc19qcus`$$
CREATE DEFINER=`ug1byw8l46zz27st`@`%` PROCEDURE `DELETE_CASO`(ID INT)
BEGIN
delete from CASO where id_caso = ID;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure DELETE_CASO_TIPO_VIOLENCIA
-- -----------------------------------------------------

DELIMITER $$
USE `bjmns7kzvsnubc19qcus`$$
CREATE DEFINER=`ug1byw8l46zz27st`@`%` PROCEDURE `DELETE_CASO_TIPO_VIOLENCIA`(IDCASO INT)
BEGIN
delete from CASO_TIPO_VIOLENCIA where id_caso = IDCASO;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure DELETE_CAUSA_VIOLENCIA
-- -----------------------------------------------------

DELIMITER $$
USE `bjmns7kzvsnubc19qcus`$$
CREATE DEFINER=`ug1byw8l46zz27st`@`%` PROCEDURE `DELETE_CAUSA_VIOLENCIA`(ID INT)
BEGIN
delete from CAUSA_VIOLENCIA where id_causa = ID;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure DELETE_ESTADO_ATENCION
-- -----------------------------------------------------

DELIMITER $$
USE `bjmns7kzvsnubc19qcus`$$
CREATE DEFINER=`ug1byw8l46zz27st`@`%` PROCEDURE `DELETE_ESTADO_ATENCION`(ID INT)
BEGIN
delete from ESTADO_ATENCION where id_estadoa = ID;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure DELETE_ESTADO_CIVIL
-- -----------------------------------------------------

DELIMITER $$
USE `bjmns7kzvsnubc19qcus`$$
CREATE DEFINER=`ug1byw8l46zz27st`@`%` PROCEDURE `DELETE_ESTADO_CIVIL`(ID INT)
BEGIN
delete from ESTADO_CIVIL where id_estadoc = ID;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure DELETE_ESTADO_OCUPACION
-- -----------------------------------------------------

DELIMITER $$
USE `bjmns7kzvsnubc19qcus`$$
CREATE DEFINER=`ug1byw8l46zz27st`@`%` PROCEDURE `DELETE_ESTADO_OCUPACION`(ID INT)
BEGIN
delete from ESTADO_OCUPACION where id_estado = ID;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure DELETE_MUNICIPIO
-- -----------------------------------------------------

DELIMITER $$
USE `bjmns7kzvsnubc19qcus`$$
CREATE DEFINER=`ug1byw8l46zz27st`@`%` PROCEDURE `DELETE_MUNICIPIO`(ID INT)
BEGIN
delete from MUNICIPIO where id_municipio = ID;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure DELETE_PACIENTE
-- -----------------------------------------------------

DELIMITER $$
USE `bjmns7kzvsnubc19qcus`$$
CREATE DEFINER=`ug1byw8l46zz27st`@`%` PROCEDURE `DELETE_PACIENTE`(ID INT)
BEGIN
delete from PACIENTE where id_paciente = ID;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure DELETE_RECURSOS_MUNICIPALES
-- -----------------------------------------------------

DELIMITER $$
USE `bjmns7kzvsnubc19qcus`$$
CREATE DEFINER=`ug1byw8l46zz27st`@`%` PROCEDURE `DELETE_RECURSOS_MUNICIPALES`(ID INT)
BEGIN
delete from RECURSOS_MUNICIPALES where id_recursos = ID;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure DELETE_REMISION
-- -----------------------------------------------------

DELIMITER $$
USE `bjmns7kzvsnubc19qcus`$$
CREATE DEFINER=`ug1byw8l46zz27st`@`%` PROCEDURE `DELETE_REMISION`(ID INT)
BEGIN
delete from REMISION where id_remision = ID;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure DELETE_TIPO_CONDICION
-- -----------------------------------------------------

DELIMITER $$
USE `bjmns7kzvsnubc19qcus`$$
CREATE DEFINER=`ug1byw8l46zz27st`@`%` PROCEDURE `DELETE_TIPO_CONDICION`(ID INT)
BEGIN
delete from TIPO_CONDICION where id_condicion = ID;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure DELETE_TIPO_VIOLENCIA
-- -----------------------------------------------------

DELIMITER $$
USE `bjmns7kzvsnubc19qcus`$$
CREATE DEFINER=`ug1byw8l46zz27st`@`%` PROCEDURE `DELETE_TIPO_VIOLENCIA`(ID INT)
BEGIN
delete from TIPO_VIOLENCIA where id_tipoviolencia = ID;

END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure DELETE_UBICACION_VIOLENCIA
-- -----------------------------------------------------

DELIMITER $$
USE `bjmns7kzvsnubc19qcus`$$
CREATE DEFINER=`ug1byw8l46zz27st`@`%` PROCEDURE `DELETE_UBICACION_VIOLENCIA`(ID INT)
BEGIN
delete from UBICACION_VIOLENCIA where id_uviolencia = ID;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure DELETE_USUARIO
-- -----------------------------------------------------

DELIMITER $$
USE `bjmns7kzvsnubc19qcus`$$
CREATE DEFINER=`ug1byw8l46zz27st`@`%` PROCEDURE `DELETE_USUARIO`(USER VARCHAR(45))
BEGIN
delete from USUARIO where usuario = USER;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure UPDATE_CASO
-- -----------------------------------------------------

DELIMITER $$
USE `bjmns7kzvsnubc19qcus`$$
CREATE DEFINER=`ug1byw8l46zz27st`@`%` PROCEDURE `UPDATE_CASO`(ID INT,NUMEXP VARCHAR(45),CANTB INT,
IDUVIO INT,IDEAT INT,IDMUNI INT,IDREMI INT,IDREC INT,IDCAUSA INT,IDTERA INT
,IDPAC INT,IDCOND INT)
BEGIN
update CASO set numero_expediente=NUMEXP,cantidad_beneficiados=CANTB,
id_uviolencia = IDUVIO,id_estadoa=IDEAT,id_municipio=IDMUNI,
id_remision=IDREMI,id_recursos=IDREC,id_causa=IDCAUSA,
id_terapeuta=IDTERA,id_paciente=IDPAC,id_condicion=IDCOND
where id_caso = ID;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure UPDATE_CASO_TIPO_VIOLENCIA
-- -----------------------------------------------------

DELIMITER $$
USE `bjmns7kzvsnubc19qcus`$$
CREATE DEFINER=`ug1byw8l46zz27st`@`%` PROCEDURE `UPDATE_CASO_TIPO_VIOLENCIA`(IDCASO INT, IDTVIO INT)
BEGIN
update CASO_TIPO_VIOLENCIA set id_tipoviolencia = IDTVIO where id_caso = IDCASO;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure UPDATE_CAUSA_VIOLENCIA
-- -----------------------------------------------------

DELIMITER $$
USE `bjmns7kzvsnubc19qcus`$$
CREATE DEFINER=`ug1byw8l46zz27st`@`%` PROCEDURE `UPDATE_CAUSA_VIOLENCIA`(ID INT,CAUSA VARCHAR(45))
BEGIN
update CAUSA_VIOLENCIA set causa = CAUSA where id_causa = ID;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure UPDATE_ESTADO_ATENCION
-- -----------------------------------------------------

DELIMITER $$
USE `bjmns7kzvsnubc19qcus`$$
CREATE DEFINER=`ug1byw8l46zz27st`@`%` PROCEDURE `UPDATE_ESTADO_ATENCION`(ID INT)
BEGIN
update ESTADO_ATENCION set estado = ESTADO where id_estadoa = ID;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure UPDATE_ESTADO_OCUPACION
-- -----------------------------------------------------

DELIMITER $$
USE `bjmns7kzvsnubc19qcus`$$
CREATE DEFINER=`ug1byw8l46zz27st`@`%` PROCEDURE `UPDATE_ESTADO_OCUPACION`(ID INT, OCUPA VARCHAR(45))
BEGIN
update ESTADO_OCUPACION set tipo = OCUPA where id_estado = ID;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure UPDATE_MUNICIPIO
-- -----------------------------------------------------

DELIMITER $$
USE `bjmns7kzvsnubc19qcus`$$
CREATE DEFINER=`ug1byw8l46zz27st`@`%` PROCEDURE `UPDATE_MUNICIPIO`(ID INT, MUNI VARCHAR(45))
BEGIN
update MUNICIPIO set nombre = MUNI where id_municipio = ID;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure UPDATE_PACIENTE
-- -----------------------------------------------------

DELIMITER $$
USE `bjmns7kzvsnubc19qcus`$$
CREATE DEFINER=`ug1byw8l46zz27st`@`%` PROCEDURE `UPDATE_PACIENTE`(ID INT,IDEN VARCHAR(15),NOMB VARCHAR(50),APELL VARCHAR(50),EDAD INT
,GENERO CHAR,OFICIO VARCHAR(45),ESTADOCIVIL INT,REMUNERA INT,EDUACION INT)
BEGIN
update PACIENTE set identidad = IDEN, nombres = NOMB, apellidos = APELL,edad = EDAD,genero = GENERO,
oficio = OFICIO, id_estadoc = ESTADOCIVIL, id_estado = REMUNERA, id_educacion = EDUACION where id_paciente = ID;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure UPDATE_RECURSOS_MUNICIPALES
-- -----------------------------------------------------

DELIMITER $$
USE `bjmns7kzvsnubc19qcus`$$
CREATE DEFINER=`ug1byw8l46zz27st`@`%` PROCEDURE `UPDATE_RECURSOS_MUNICIPALES`(ID INT, RECURSO VARCHAR(45))
BEGIN
update RECURSOS_MUNICIPALES set tipo = RECURSO where id_recursos=ID;

END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure UPDATE_TERAPEUTA
-- -----------------------------------------------------

DELIMITER $$
USE `bjmns7kzvsnubc19qcus`$$
CREATE DEFINER=`ug1byw8l46zz27st`@`%` PROCEDURE `UPDATE_TERAPEUTA`(ID INT, NOMB VARCHAR(45))
BEGIN
update TERAPEUTA set nombre = NOMB where id_terapeuta = ID;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure UPDATE_TIPO_CONDICION
-- -----------------------------------------------------

DELIMITER $$
USE `bjmns7kzvsnubc19qcus`$$
CREATE DEFINER=`ug1byw8l46zz27st`@`%` PROCEDURE `UPDATE_TIPO_CONDICION`(ID INT,COND VARCHAR(45))
BEGIN
update TIPO_CONDICION set condicion = COND where id_condicion = ID;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure UPDATE_TIPO_VIOLENCIA
-- -----------------------------------------------------

DELIMITER $$
USE `bjmns7kzvsnubc19qcus`$$
CREATE DEFINER=`ug1byw8l46zz27st`@`%` PROCEDURE `UPDATE_TIPO_VIOLENCIA`(ID INT,TIPOV VARCHAR(45))
BEGIN
update TIPO_VIOLENCIA set tipo = TIPOV where id_tipoviolencia = ID;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure UPDATE_UBICACION_VIOLENCIA
-- -----------------------------------------------------

DELIMITER $$
USE `bjmns7kzvsnubc19qcus`$$
CREATE DEFINER=`ug1byw8l46zz27st`@`%` PROCEDURE `UPDATE_UBICACION_VIOLENCIA`(ID INT,UVIOLENCIA VARCHAR(45))
BEGIN
update UBICACION_VIOLENCIA set ubicacion = UVIOLENCIA where id_uviolencia = ID;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure UPDATE_USUARIO
-- -----------------------------------------------------

DELIMITER $$
USE `bjmns7kzvsnubc19qcus`$$
CREATE DEFINER=`ug1byw8l46zz27st`@`%` PROCEDURE `UPDATE_USUARIO`(USER VARCHAR(45),PASS VARCHAR(45),NUSER VARCHAR(45))
BEGIN
update USUARIO set usuario = NUSER, contraseña = PASS where usuario = USER;

END$$

DELIMITER ;

-- -----------------------------------------------------
-- View `bjmns7kzvsnubc19qcus`.`VIEW_CASO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bjmns7kzvsnubc19qcus`.`VIEW_CASO`;
USE `bjmns7kzvsnubc19qcus`;
CREATE  OR REPLACE ALGORITHM=UNDEFINED DEFINER=`ug1byw8l46zz27st`@`%` SQL SECURITY DEFINER VIEW `bjmns7kzvsnubc19qcus`.`VIEW_CASO` AS select concat(`pc`.`nombres`,' ',`pc`.`apellidos`) AS `nombre`,`tc`.`condicion` AS `condicion`,`tr`.`nombre` AS `terapeuta`,`cv`.`causa` AS `causa`,`rmp`.`tipo` AS `recursos`,`rm`.`juez` AS `juez`,`mn`.`nombre` AS `municipio`,`ea`.`estado` AS `estado_atencion`,`uv`.`ubicacion` AS `ubicacion_violencia` from (((((((((`bjmns7kzvsnubc19qcus`.`CASO` `cs` join `bjmns7kzvsnubc19qcus`.`UBICACION_VIOLENCIA` `uv` on((`cs`.`id_uviolencia` = `uv`.`id_uviolencia`))) join `bjmns7kzvsnubc19qcus`.`ESTADO_ATENCION` `ea` on((`cs`.`id_estadoa` = `ea`.`id_estadoa`))) join `bjmns7kzvsnubc19qcus`.`MUNICIPIO` `mn` on((`cs`.`id_municipio` = `mn`.`id_municipio`))) join `bjmns7kzvsnubc19qcus`.`REMISION` `rm` on((`cs`.`id_remision` = `rm`.`id_remision`))) join `bjmns7kzvsnubc19qcus`.`RECURSOS_MUNICIPALES` `rmp` on((`cs`.`id_recursos` = `rmp`.`id_recursos`))) join `bjmns7kzvsnubc19qcus`.`CAUSA_VIOLENCIA` `cv` on((`cs`.`id_causa` = `cv`.`id_causa`))) join `bjmns7kzvsnubc19qcus`.`TERAPEUTA` `tr` on((`cs`.`id_terapeuta` = `tr`.`id_terapeuta`))) join `bjmns7kzvsnubc19qcus`.`PACIENTE` `pc` on((`cs`.`id_paciente` = `pc`.`id_paciente`))) join `bjmns7kzvsnubc19qcus`.`TIPO_CONDICION` `tc` on((`cs`.`id_condicion` = `tc`.`id_condicion`)));

-- -----------------------------------------------------
-- View `bjmns7kzvsnubc19qcus`.`VIEW_CAUSA_VIOLENCIA`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bjmns7kzvsnubc19qcus`.`VIEW_CAUSA_VIOLENCIA`;
USE `bjmns7kzvsnubc19qcus`;
CREATE  OR REPLACE ALGORITHM=UNDEFINED DEFINER=`ug1byw8l46zz27st`@`%` SQL SECURITY DEFINER VIEW `bjmns7kzvsnubc19qcus`.`VIEW_CAUSA_VIOLENCIA` AS select `bjmns7kzvsnubc19qcus`.`CAUSA_VIOLENCIA`.`id_causa` AS `id_causa`,`bjmns7kzvsnubc19qcus`.`CAUSA_VIOLENCIA`.`causa` AS `causa` from `bjmns7kzvsnubc19qcus`.`CAUSA_VIOLENCIA`;

-- -----------------------------------------------------
-- View `bjmns7kzvsnubc19qcus`.`VIEW_EDUCACION`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bjmns7kzvsnubc19qcus`.`VIEW_EDUCACION`;
USE `bjmns7kzvsnubc19qcus`;
CREATE  OR REPLACE ALGORITHM=UNDEFINED DEFINER=`ug1byw8l46zz27st`@`%` SQL SECURITY DEFINER VIEW `bjmns7kzvsnubc19qcus`.`VIEW_EDUCACION` AS select `bjmns7kzvsnubc19qcus`.`EDUCACION`.`id_educacion` AS `id_educacion`,`bjmns7kzvsnubc19qcus`.`EDUCACION`.`tipo` AS `tipo` from `bjmns7kzvsnubc19qcus`.`EDUCACION`;

-- -----------------------------------------------------
-- View `bjmns7kzvsnubc19qcus`.`VIEW_ESTADO_ATENCION`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bjmns7kzvsnubc19qcus`.`VIEW_ESTADO_ATENCION`;
USE `bjmns7kzvsnubc19qcus`;
CREATE  OR REPLACE ALGORITHM=UNDEFINED DEFINER=`ug1byw8l46zz27st`@`%` SQL SECURITY DEFINER VIEW `bjmns7kzvsnubc19qcus`.`VIEW_ESTADO_ATENCION` AS select `bjmns7kzvsnubc19qcus`.`ESTADO_ATENCION`.`id_estadoa` AS `id_estadoa`,`bjmns7kzvsnubc19qcus`.`ESTADO_ATENCION`.`estado` AS `estado` from `bjmns7kzvsnubc19qcus`.`ESTADO_ATENCION`;

-- -----------------------------------------------------
-- View `bjmns7kzvsnubc19qcus`.`VIEW_ESTADO_CIVIL`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bjmns7kzvsnubc19qcus`.`VIEW_ESTADO_CIVIL`;
USE `bjmns7kzvsnubc19qcus`;
CREATE  OR REPLACE ALGORITHM=UNDEFINED DEFINER=`ug1byw8l46zz27st`@`%` SQL SECURITY DEFINER VIEW `bjmns7kzvsnubc19qcus`.`VIEW_ESTADO_CIVIL` AS select `bjmns7kzvsnubc19qcus`.`ESTADO_CIVIL`.`id_estadoc` AS `id_estadoc`,`bjmns7kzvsnubc19qcus`.`ESTADO_CIVIL`.`estado` AS `estado` from `bjmns7kzvsnubc19qcus`.`ESTADO_CIVIL`;

-- -----------------------------------------------------
-- View `bjmns7kzvsnubc19qcus`.`VIEW_ESTADO_OCUPACION`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bjmns7kzvsnubc19qcus`.`VIEW_ESTADO_OCUPACION`;
USE `bjmns7kzvsnubc19qcus`;
CREATE  OR REPLACE ALGORITHM=UNDEFINED DEFINER=`ug1byw8l46zz27st`@`%` SQL SECURITY DEFINER VIEW `bjmns7kzvsnubc19qcus`.`VIEW_ESTADO_OCUPACION` AS select `bjmns7kzvsnubc19qcus`.`ESTADO_OCUPACION`.`id_estado` AS `id_estado`,`bjmns7kzvsnubc19qcus`.`ESTADO_OCUPACION`.`tipo` AS `tipo` from `bjmns7kzvsnubc19qcus`.`ESTADO_OCUPACION`;

-- -----------------------------------------------------
-- View `bjmns7kzvsnubc19qcus`.`VIEW_MUNICIPIO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bjmns7kzvsnubc19qcus`.`VIEW_MUNICIPIO`;
USE `bjmns7kzvsnubc19qcus`;
CREATE  OR REPLACE ALGORITHM=UNDEFINED DEFINER=`ug1byw8l46zz27st`@`%` SQL SECURITY DEFINER VIEW `bjmns7kzvsnubc19qcus`.`VIEW_MUNICIPIO` AS select `bjmns7kzvsnubc19qcus`.`MUNICIPIO`.`id_municipio` AS `id_municipio`,`bjmns7kzvsnubc19qcus`.`MUNICIPIO`.`nombre` AS `nombre` from `bjmns7kzvsnubc19qcus`.`MUNICIPIO`;

-- -----------------------------------------------------
-- View `bjmns7kzvsnubc19qcus`.`VIEW_PACIENTE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bjmns7kzvsnubc19qcus`.`VIEW_PACIENTE`;
USE `bjmns7kzvsnubc19qcus`;
CREATE  OR REPLACE ALGORITHM=UNDEFINED DEFINER=`ug1byw8l46zz27st`@`%` SQL SECURITY DEFINER VIEW `bjmns7kzvsnubc19qcus`.`VIEW_PACIENTE` AS select `pc`.`identidad` AS `identidad`,`pc`.`nombres` AS `nombre`,`pc`.`apellidos` AS `apellido`,`pc`.`edad` AS `edad`,`pc`.`genero` AS `genero`,`pc`.`oficio` AS `oficio`,`ec`.`estado` AS `estado_civil`,`eo`.`tipo` AS `trabajo`,`ed`.`tipo` AS `educacion` from (((`bjmns7kzvsnubc19qcus`.`PACIENTE` `pc` join `bjmns7kzvsnubc19qcus`.`ESTADO_CIVIL` `ec` on((`pc`.`id_estadoc` = `ec`.`id_estadoc`))) join `bjmns7kzvsnubc19qcus`.`ESTADO_OCUPACION` `eo` on((`pc`.`id_estado` = `eo`.`id_estado`))) join `bjmns7kzvsnubc19qcus`.`EDUCACION` `ed` on((`pc`.`id_educacion` = `ed`.`id_educacion`)));

-- -----------------------------------------------------
-- View `bjmns7kzvsnubc19qcus`.`VIEW_RECURSOS_MUNICIPALES`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bjmns7kzvsnubc19qcus`.`VIEW_RECURSOS_MUNICIPALES`;
USE `bjmns7kzvsnubc19qcus`;
CREATE  OR REPLACE ALGORITHM=UNDEFINED DEFINER=`ug1byw8l46zz27st`@`%` SQL SECURITY DEFINER VIEW `bjmns7kzvsnubc19qcus`.`VIEW_RECURSOS_MUNICIPALES` AS select `bjmns7kzvsnubc19qcus`.`RECURSOS_MUNICIPALES`.`id_recursos` AS `id_recursos`,`bjmns7kzvsnubc19qcus`.`RECURSOS_MUNICIPALES`.`tipo` AS `tipo` from `bjmns7kzvsnubc19qcus`.`RECURSOS_MUNICIPALES`;

-- -----------------------------------------------------
-- View `bjmns7kzvsnubc19qcus`.`VIEW_REMISION`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bjmns7kzvsnubc19qcus`.`VIEW_REMISION`;
USE `bjmns7kzvsnubc19qcus`;
CREATE  OR REPLACE ALGORITHM=UNDEFINED DEFINER=`ug1byw8l46zz27st`@`%` SQL SECURITY DEFINER VIEW `bjmns7kzvsnubc19qcus`.`VIEW_REMISION` AS select `bjmns7kzvsnubc19qcus`.`RECURSOS_MUNICIPALES`.`id_recursos` AS `id_recursos`,`bjmns7kzvsnubc19qcus`.`RECURSOS_MUNICIPALES`.`tipo` AS `tipo` from `bjmns7kzvsnubc19qcus`.`RECURSOS_MUNICIPALES`;

-- -----------------------------------------------------
-- View `bjmns7kzvsnubc19qcus`.`VIEW_TERAPEUTA`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bjmns7kzvsnubc19qcus`.`VIEW_TERAPEUTA`;
USE `bjmns7kzvsnubc19qcus`;
CREATE  OR REPLACE ALGORITHM=UNDEFINED DEFINER=`ug1byw8l46zz27st`@`%` SQL SECURITY DEFINER VIEW `bjmns7kzvsnubc19qcus`.`VIEW_TERAPEUTA` AS select `bjmns7kzvsnubc19qcus`.`TERAPEUTA`.`id_terapeuta` AS `id_terapeuta`,`bjmns7kzvsnubc19qcus`.`TERAPEUTA`.`nombre` AS `nombre` from `bjmns7kzvsnubc19qcus`.`TERAPEUTA`;

-- -----------------------------------------------------
-- View `bjmns7kzvsnubc19qcus`.`VIEW_TIPO_CONDICION`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bjmns7kzvsnubc19qcus`.`VIEW_TIPO_CONDICION`;
USE `bjmns7kzvsnubc19qcus`;
CREATE  OR REPLACE ALGORITHM=UNDEFINED DEFINER=`ug1byw8l46zz27st`@`%` SQL SECURITY DEFINER VIEW `bjmns7kzvsnubc19qcus`.`VIEW_TIPO_CONDICION` AS select `bjmns7kzvsnubc19qcus`.`TIPO_CONDICION`.`id_condicion` AS `id_condicion`,`bjmns7kzvsnubc19qcus`.`TIPO_CONDICION`.`condicion` AS `condicion` from `bjmns7kzvsnubc19qcus`.`TIPO_CONDICION`;

-- -----------------------------------------------------
-- View `bjmns7kzvsnubc19qcus`.`VIEW_TIPO_VIOLENCIA`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bjmns7kzvsnubc19qcus`.`VIEW_TIPO_VIOLENCIA`;
USE `bjmns7kzvsnubc19qcus`;
CREATE  OR REPLACE ALGORITHM=UNDEFINED DEFINER=`ug1byw8l46zz27st`@`%` SQL SECURITY DEFINER VIEW `bjmns7kzvsnubc19qcus`.`VIEW_TIPO_VIOLENCIA` AS select `bjmns7kzvsnubc19qcus`.`TIPO_VIOLENCIA`.`id_tipoviolencia` AS `id_tipoviolencia`,`bjmns7kzvsnubc19qcus`.`TIPO_VIOLENCIA`.`tipo` AS `tipo` from `bjmns7kzvsnubc19qcus`.`TIPO_VIOLENCIA`;

-- -----------------------------------------------------
-- View `bjmns7kzvsnubc19qcus`.`VIEW_UBICACION_VIOLENCIA`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bjmns7kzvsnubc19qcus`.`VIEW_UBICACION_VIOLENCIA`;
USE `bjmns7kzvsnubc19qcus`;
CREATE  OR REPLACE ALGORITHM=UNDEFINED DEFINER=`ug1byw8l46zz27st`@`%` SQL SECURITY DEFINER VIEW `bjmns7kzvsnubc19qcus`.`VIEW_UBICACION_VIOLENCIA` AS select `bjmns7kzvsnubc19qcus`.`UBICACION_VIOLENCIA`.`id_uviolencia` AS `id_uviolencia`,`bjmns7kzvsnubc19qcus`.`UBICACION_VIOLENCIA`.`ubicacion` AS `ubicacion` from `bjmns7kzvsnubc19qcus`.`UBICACION_VIOLENCIA`;

-- -----------------------------------------------------
-- View `bjmns7kzvsnubc19qcus`.`VIEW_USUARIO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bjmns7kzvsnubc19qcus`.`VIEW_USUARIO`;
USE `bjmns7kzvsnubc19qcus`;
CREATE  OR REPLACE ALGORITHM=UNDEFINED DEFINER=`ug1byw8l46zz27st`@`%` SQL SECURITY DEFINER VIEW `bjmns7kzvsnubc19qcus`.`VIEW_USUARIO` AS select `bjmns7kzvsnubc19qcus`.`USUARIO`.`usuario` AS `usuario`,`bjmns7kzvsnubc19qcus`.`USUARIO`.`contraseña` AS `contraseña` from `bjmns7kzvsnubc19qcus`.`USUARIO`;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
